version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    vendor: true
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
