[files]
extend-exclude = [
  "vendor/**",
  "go.mod"
]

[default.extend-identifiers]
vas = "vas"
splitted = "splitted"

[default.extend-words]
# Hash-related typo
cace = "cace"
Wqs = "Wqs"

# Domain examples
exmaple = "exmaple"

# CLI-related typos
doct = "doctl"
doclt = "doctl"
doctl' = "doctl"
doctl;s = "doctl’s"
doctl 's = "doctl’s"
doctl`s = "doctl’s"
doctl’ss = "doctl’s"

# Markdown formatting quirks
`doctl`'s = "doctl’s"
`doctl` ’s = "doctl’s"
`doctl`' = "doctl’s"

# Common contributor typos
intial = "initial"
recieve = "receive"
teh = "the"
enviroment = "environment"
