package doit

const (
	ArgActionID          = "action-id"
	ArgDomainName        = "domain-name"
	ArgDropletID         = "droplet-id"
	ArgKernelID          = "kernel-id"
	ArgImage             = "image"
	ArgImageID           = "image-id"
	ArgImagePublic       = "public"
	ArgImageSlug         = "image-slug"
	ArgIPAddress         = "ip-address"
	ArgDropletName       = "droplet-name"
	ArgResizeDisk        = "resize-disk"
	ArgSnapshotName      = "snapshot-name"
	ArgBackups           = "enable-backups"
	ArgIPv6              = "enable-ipv6"
	ArgPrivateNetworking = "enable-private-networking"
	ArgRecordData        = "record-data"
	ArgRecordID          = "record-id"
	ArgRecordName        = "record-name"
	ArgRecordPort        = "record-port"
	ArgRecordPriority    = "record-priority"
	ArgRecordType        = "record-type"
	ArgRecordWeight      = "record-weight"
	ArgRegionSlug        = "region"
	ArgSizeSlug          = "size"
	ArgSSHKeys           = "ssh-keys"
	ArgSSHOption         = "o"
	ArgUserData          = "user-data"
	ArgUserDataFile      = "user-data-file"
	ArgImageName         = "image-name"
	ArgKey               = "key"
	ArgKeyName           = "key-name"
	ArgKeyPublicKey      = "public-key"
	ArgKeyPublicKeyFile  = "public-key-file"
	ArgSSHUser           = "ssh-user"

	// Arguments for outputs
	ArgOutput = "output"
)
