FROM doctl_builder

ENV CGO=0
ENV OUT_D /out

RUN mkdir -p /out
RUN mkdir -p /go/src/github.com/digitalocean/doctl
ADD . /go/src/github.com/digitalocean/doctl/

RUN cd /go/src/github.com/digitalocean/doctl && \
    make _build_linux_amd64 OUT=/out

RUN find /out

FROM alpine:latest

VOLUME ["/copy"]

RUN apk add --update \
        rsync \
        libc6-compat \
        openssh \
        ca-certificates


COPY --from=0 /out/* /app/

ENTRYPOINT ["/app/doctl_linux_amd64"]
