FROM alpine:3.8

RUN apk add --update \
        bash \
        curl \
        rsync \
        libc6-compat \
        openssh \
        ca-certificates

WORKDIR /app

COPY doctl .

ENTRYPOINT ["./doctl"]
