name: doctl
version: 0
summary: A command line tool for DigitalOcean services
description: doctl is a command line interface for the DigitalOcean API.
confinement: strict

apps:
    doctl:
        command: bin/doctl
        plugs:
            - network
 
parts:
    doctl-build:
        plugin: x-build-sh
        source: .
        organize:
            out/doctl: bin/doctl
