// Code generated by MockGen. DO NOT EDIT.
// Source: gradientai.go
//
// Generated by this command:
//
//	mockgen -source gradientai.go -package=mocks AgentPlatformService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentPlatformService is a mock of AgentPlatformService interface.
type MockAgentPlatformService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPlatformServiceMockRecorder
	isgomock struct{}
}

// MockAgentPlatformServiceMockRecorder is the mock recorder for MockAgentPlatformService.
type MockAgentPlatformServiceMockRecorder struct {
	mock *MockAgentPlatformService
}

// NewMockAgentPlatformService creates a new mock instance.
func NewMockAgentPlatformService(ctrl *gomock.Controller) *MockAgentPlatformService {
	mock := &MockAgentPlatformService{ctrl: ctrl}
	mock.recorder = &MockAgentPlatformServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPlatformService) EXPECT() *MockAgentPlatformServiceMockRecorder {
	return m.recorder
}

// AddKnowledgeBaseDataSource mocks base method.
func (m *MockAgentPlatformService) AddKnowledgeBaseDataSource(knowledgeBaseID string, req *godo.AddKnowledgeBaseDataSourceRequest) (*do.KnowledgeBaseDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledgeBaseDataSource", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKnowledgeBaseDataSource indicates an expected call of AddKnowledgeBaseDataSource.
func (mr *MockAgentPlatformServiceMockRecorder) AddKnowledgeBaseDataSource(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledgeBaseDataSource", reflect.TypeOf((*MockAgentPlatformService)(nil).AddKnowledgeBaseDataSource), knowledgeBaseID, req)
}

// AttachKnowledgeBaseToAgent mocks base method.
func (m *MockAgentPlatformService) AttachKnowledgeBaseToAgent(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachKnowledgeBaseToAgent", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachKnowledgeBaseToAgent indicates an expected call of AttachKnowledgeBaseToAgent.
func (mr *MockAgentPlatformServiceMockRecorder) AttachKnowledgeBaseToAgent(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachKnowledgeBaseToAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).AttachKnowledgeBaseToAgent), agentId, knowledgeBaseID)
}

// CancelIndexingJob mocks base method.
func (m *MockAgentPlatformService) CancelIndexingJob(indexingJobID string) (*do.IndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIndexingJob", indexingJobID)
	ret0, _ := ret[0].(*do.IndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelIndexingJob indicates an expected call of CancelIndexingJob.
func (mr *MockAgentPlatformServiceMockRecorder) CancelIndexingJob(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIndexingJob", reflect.TypeOf((*MockAgentPlatformService)(nil).CancelIndexingJob), indexingJobID)
}

// CancelModelEvaluationRun mocks base method.
func (m *MockGradientAIService) CancelModelEvaluationRun(evalRunUUID string) (*do.ModelEvaluationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelModelEvaluationRun", evalRunUUID)
	ret0, _ := ret[0].(*do.ModelEvaluationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelModelEvaluationRun indicates an expected call of CancelModelEvaluationRun.
func (mr *MockGradientAIServiceMockRecorder) CancelModelEvaluationRun(evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelModelEvaluationRun", reflect.TypeOf((*MockGradientAIService)(nil).CancelModelEvaluationRun), evalRunUUID)
}

// CancelSimulationRun mocks base method.
func (m *MockAgentPlatformService) CancelSimulationRun(runUUID string) (*do.SimulationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSimulationRun", runUUID)
	ret0, _ := ret[0].(*do.SimulationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelSimulationRun indicates an expected call of CancelSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CancelSimulationRun(runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CancelSimulationRun), runUUID)
}

// CreateCustomEvaluationMetric mocks base method.
func (m *MockGradientAIService) CreateCustomEvaluationMetric(req *godo.CreateCustomEvaluationMetricRequest) (*do.EvaluationMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomEvaluationMetric", req)
	ret0, _ := ret[0].(*do.EvaluationMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomEvaluationMetric indicates an expected call of CreateCustomEvaluationMetric.
func (mr *MockGradientAIServiceMockRecorder) CreateCustomEvaluationMetric(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomEvaluationMetric", reflect.TypeOf((*MockGradientAIService)(nil).CreateCustomEvaluationMetric), req)
}

// CreateEvaluationDataset mocks base method.
func (m *MockGradientAIService) CreateEvaluationDataset(req *godo.CreateEvaluationDatasetRequest) (*do.EvaluationDatasetCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvaluationDataset", req)
	ret0, _ := ret[0].(*do.EvaluationDatasetCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvaluationDataset indicates an expected call of CreateEvaluationDataset.
func (mr *MockGradientAIServiceMockRecorder) CreateEvaluationDataset(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvaluationDataset", reflect.TypeOf((*MockGradientAIService)(nil).CreateEvaluationDataset), req)
}

// CreateKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) CreateKnowledgeBase(req *godo.KnowledgeBaseCreateRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) CreateKnowledgeBase(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateKnowledgeBase), req)
}

// CreateModelEvalDatasetUploadPresignedURLs mocks base method.
func (m *MockGradientAIService) CreateModelEvalDatasetUploadPresignedURLs(req *godo.CreateModelEvalDatasetUploadPresignedURLsRequest) (*do.ModelEvalDatasetFileUploads, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelEvalDatasetUploadPresignedURLs", req)
	ret0, _ := ret[0].(*do.ModelEvalDatasetFileUploads)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelEvalDatasetUploadPresignedURLs indicates an expected call of CreateModelEvalDatasetUploadPresignedURLs.
func (mr *MockGradientAIServiceMockRecorder) CreateModelEvalDatasetUploadPresignedURLs(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelEvalDatasetUploadPresignedURLs", reflect.TypeOf((*MockGradientAIService)(nil).CreateModelEvalDatasetUploadPresignedURLs), req)
}

// CreateModelEvaluationRun mocks base method.
func (m *MockGradientAIService) CreateModelEvaluationRun(req *godo.CreateModelEvaluationRunRequest) (*do.ModelEvaluationRunCreate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelEvaluationRun", req)
	ret0, _ := ret[0].(*do.ModelEvaluationRunCreate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelEvaluationRun indicates an expected call of CreateModelEvaluationRun.
func (mr *MockGradientAIServiceMockRecorder) CreateModelEvaluationRun(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelEvaluationRun", reflect.TypeOf((*MockGradientAIService)(nil).CreateModelEvaluationRun), req)
}

// CreateOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) CreateOpenAIAPIKey(openaiAPIKeyCreate *godo.OpenAIAPIKeyCreateRequest) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenAIAPIKey", openaiAPIKeyCreate)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpenAIAPIKey indicates an expected call of CreateOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) CreateOpenAIAPIKey(openaiAPIKeyCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateOpenAIAPIKey), openaiAPIKeyCreate)
}

// CreateScenarioSet mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSet(req *godo.CreateScenarioSetRequest) (*do.ScenarioSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSet", req)
	ret0, _ := ret[0].(*do.ScenarioSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScenarioSet indicates an expected call of CreateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSet(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSet), req)
}

// CreateScenarioSetFromLibrary mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSetFromLibrary(libraryScenarioUUID string, req *godo.CreateScenarioSetFromLibraryRequest) (*do.ScenarioSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSetFromLibrary", libraryScenarioUUID, req)
	ret0, _ := ret[0].(*do.ScenarioSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScenarioSetFromLibrary indicates an expected call of CreateScenarioSetFromLibrary.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSetFromLibrary(libraryScenarioUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSetFromLibrary", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSetFromLibrary), libraryScenarioUUID, req)
}

// CreateScenarioSetUploadPresignedURLs mocks base method.
func (m *MockAgentPlatformService) CreateScenarioSetUploadPresignedURLs(req *godo.CreateScenarioSetUploadPresignedURLsRequest) (*do.ScenarioSetFileUploads, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenarioSetUploadPresignedURLs", req)
	ret0, _ := ret[0].(*do.ScenarioSetFileUploads)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScenarioSetUploadPresignedURLs indicates an expected call of CreateScenarioSetUploadPresignedURLs.
func (mr *MockAgentPlatformServiceMockRecorder) CreateScenarioSetUploadPresignedURLs(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenarioSetUploadPresignedURLs", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateScenarioSetUploadPresignedURLs), req)
}

// CreateSimulationRun mocks base method.
func (m *MockAgentPlatformService) CreateSimulationRun(req *godo.CreateSimulationRunRequest) (*do.SimulationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimulationRun", req)
	ret0, _ := ret[0].(*do.SimulationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSimulationRun indicates an expected call of CreateSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) CreateSimulationRun(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).CreateSimulationRun), req)
}

// DeleteCustomEvaluationMetric mocks base method.
func (m *MockGradientAIService) DeleteCustomEvaluationMetric(metricUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomEvaluationMetric", metricUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomEvaluationMetric indicates an expected call of DeleteCustomEvaluationMetric.
func (mr *MockGradientAIServiceMockRecorder) DeleteCustomEvaluationMetric(metricUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomEvaluationMetric", reflect.TypeOf((*MockGradientAIService)(nil).DeleteCustomEvaluationMetric), metricUUID)
}

// DeleteEvaluationDataset mocks base method.
func (m *MockGradientAIService) DeleteEvaluationDataset(datasetUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvaluationDataset", datasetUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvaluationDataset indicates an expected call of DeleteEvaluationDataset.
func (mr *MockGradientAIServiceMockRecorder) DeleteEvaluationDataset(datasetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvaluationDataset", reflect.TypeOf((*MockGradientAIService)(nil).DeleteEvaluationDataset), datasetUUID)
}

// DeleteKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) DeleteKnowledgeBase(knowledgeBaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBase", knowledgeBaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeBase indicates an expected call of DeleteKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteKnowledgeBase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteKnowledgeBase), knowledgeBaseID)
}

// DeleteKnowledgeBaseDataSource mocks base method.
func (m *MockAgentPlatformService) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBaseDataSource", knowledgeBaseID, dataSourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeBaseDataSource indicates an expected call of DeleteKnowledgeBaseDataSource.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBaseDataSource", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteKnowledgeBaseDataSource), knowledgeBaseID, dataSourceID)
}

// DeleteModelEvaluationPreset mocks base method.
func (m *MockGradientAIService) DeleteModelEvaluationPreset(evalPresetUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelEvaluationPreset", evalPresetUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModelEvaluationPreset indicates an expected call of DeleteModelEvaluationPreset.
func (mr *MockGradientAIServiceMockRecorder) DeleteModelEvaluationPreset(evalPresetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelEvaluationPreset", reflect.TypeOf((*MockGradientAIService)(nil).DeleteModelEvaluationPreset), evalPresetUUID)
}

// DeleteModelEvaluationRun mocks base method.
func (m *MockGradientAIService) DeleteModelEvaluationRun(evalRunUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelEvaluationRun", evalRunUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModelEvaluationRun indicates an expected call of DeleteModelEvaluationRun.
func (mr *MockGradientAIServiceMockRecorder) DeleteModelEvaluationRun(evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelEvaluationRun", reflect.TypeOf((*MockGradientAIService)(nil).DeleteModelEvaluationRun), evalRunUUID)
}

// DeleteOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) DeleteOpenAIAPIKey(openaiApiKeyId string) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOpenAIAPIKey indicates an expected call of DeleteOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteOpenAIAPIKey), openaiApiKeyId)
}

// DeleteScenarioSet mocks base method.
func (m *MockAgentPlatformService) DeleteScenarioSet(scenarioSetUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScenarioSet", scenarioSetUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScenarioSet indicates an expected call of DeleteScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteScenarioSet(scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteScenarioSet), scenarioSetUUID)
}

// DeleteSimulationRun mocks base method.
func (m *MockAgentPlatformService) DeleteSimulationRun(runUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSimulationRun", runUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSimulationRun indicates an expected call of DeleteSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) DeleteSimulationRun(runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).DeleteSimulationRun), runUUID)
}

// DetachKnowledgeBaseToAgent mocks base method.
func (m *MockAgentPlatformService) DetachKnowledgeBaseToAgent(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachKnowledgeBaseToAgent", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachKnowledgeBaseToAgent indicates an expected call of DetachKnowledgeBaseToAgent.
func (mr *MockAgentPlatformServiceMockRecorder) DetachKnowledgeBaseToAgent(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachKnowledgeBaseToAgent", reflect.TypeOf((*MockAgentPlatformService)(nil).DetachKnowledgeBaseToAgent), agentId, knowledgeBaseID)
}

// GenerateScenarioSet mocks base method.
func (m *MockAgentPlatformService) GenerateScenarioSet(req *godo.GenerateScenarioSetRequest) (*do.ScenarioSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateScenarioSet", req)
	ret0, _ := ret[0].(*do.ScenarioSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateScenarioSet indicates an expected call of GenerateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) GenerateScenarioSet(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).GenerateScenarioSet), req)
}

// GetIndexingJob mocks base method.
func (m *MockAgentPlatformService) GetIndexingJob(indexingJobID string) (*do.IndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingJob", indexingJobID)
	ret0, _ := ret[0].(*do.IndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexingJob indicates an expected call of GetIndexingJob.
func (mr *MockAgentPlatformServiceMockRecorder) GetIndexingJob(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingJob", reflect.TypeOf((*MockAgentPlatformService)(nil).GetIndexingJob), indexingJobID)
}

// GetKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) GetKnowledgeBase(knowledgeBaseID string) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", knowledgeBaseID)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) GetKnowledgeBase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).GetKnowledgeBase), knowledgeBaseID)
}

// GetModelEvaluationPreset mocks base method.
func (m *MockGradientAIService) GetModelEvaluationPreset(evalPresetUUID string) (*do.ModelEvaluationPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationPreset", evalPresetUUID)
	ret0, _ := ret[0].(*do.ModelEvaluationPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelEvaluationPreset indicates an expected call of GetModelEvaluationPreset.
func (mr *MockGradientAIServiceMockRecorder) GetModelEvaluationPreset(evalPresetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationPreset", reflect.TypeOf((*MockGradientAIService)(nil).GetModelEvaluationPreset), evalPresetUUID)
}

// GetModelEvaluationRun mocks base method.
func (m *MockGradientAIService) GetModelEvaluationRun(evalRunUUID string) (*do.ModelEvaluationRunDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationRun", evalRunUUID)
	ret0, _ := ret[0].(*do.ModelEvaluationRunDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelEvaluationRun indicates an expected call of GetModelEvaluationRun.
func (mr *MockGradientAIServiceMockRecorder) GetModelEvaluationRun(evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationRun", reflect.TypeOf((*MockGradientAIService)(nil).GetModelEvaluationRun), evalRunUUID)
}

// GetModelEvaluationRunResultsDownloadURL mocks base method.
func (m *MockGradientAIService) GetModelEvaluationRunResultsDownloadURL(evalRunUUID string) (*do.GenAIDownloadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelEvaluationRunResultsDownloadURL", evalRunUUID)
	ret0, _ := ret[0].(*do.GenAIDownloadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelEvaluationRunResultsDownloadURL indicates an expected call of GetModelEvaluationRunResultsDownloadURL.
func (mr *MockGradientAIServiceMockRecorder) GetModelEvaluationRunResultsDownloadURL(evalRunUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelEvaluationRunResultsDownloadURL", reflect.TypeOf((*MockGradientAIService)(nil).GetModelEvaluationRunResultsDownloadURL), evalRunUUID)
}

// GetOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) GetOpenAIAPIKey(openaiApiKeyId string) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenAIAPIKey indicates an expected call of GetOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) GetOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).GetOpenAIAPIKey), openaiApiKeyId)
}

// GetScenarioSet mocks base method.
func (m *MockAgentPlatformService) GetScenarioSet(scenarioSetUUID string) (*do.ScenarioSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenarioSet", scenarioSetUUID)
	ret0, _ := ret[0].(*do.ScenarioSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScenarioSet indicates an expected call of GetScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) GetScenarioSet(scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).GetScenarioSet), scenarioSetUUID)
}

// GetScenarioSetDownloadURL mocks base method.
func (m *MockAgentPlatformService) GetScenarioSetDownloadURL(scenarioSetUUID string) (*do.GenAIDownloadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenarioSetDownloadURL", scenarioSetUUID)
	ret0, _ := ret[0].(*do.GenAIDownloadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScenarioSetDownloadURL indicates an expected call of GetScenarioSetDownloadURL.
func (mr *MockAgentPlatformServiceMockRecorder) GetScenarioSetDownloadURL(scenarioSetUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenarioSetDownloadURL", reflect.TypeOf((*MockAgentPlatformService)(nil).GetScenarioSetDownloadURL), scenarioSetUUID)
}

// GetSimulationJourney mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourney(runUUID, journeyUUID string) (*do.SimulationJourney, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourney", runUUID, journeyUUID)
	ret0, _ := ret[0].(*do.SimulationJourney)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulationJourney indicates an expected call of GetSimulationJourney.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourney(runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourney", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourney), runUUID, journeyUUID)
}

// GetSimulationJourneyTrajectory mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourneyTrajectory(runUUID, journeyUUID string) (*do.SimulationTrajectory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourneyTrajectory", runUUID, journeyUUID)
	ret0, _ := ret[0].(*do.SimulationTrajectory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulationJourneyTrajectory indicates an expected call of GetSimulationJourneyTrajectory.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourneyTrajectory(runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourneyTrajectory", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourneyTrajectory), runUUID, journeyUUID)
}

// GetSimulationJourneyTrajectoryURL mocks base method.
func (m *MockAgentPlatformService) GetSimulationJourneyTrajectoryURL(runUUID, journeyUUID string) (*do.GenAIDownloadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationJourneyTrajectoryURL", runUUID, journeyUUID)
	ret0, _ := ret[0].(*do.GenAIDownloadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulationJourneyTrajectoryURL indicates an expected call of GetSimulationJourneyTrajectoryURL.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationJourneyTrajectoryURL(runUUID, journeyUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationJourneyTrajectoryURL", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationJourneyTrajectoryURL), runUUID, journeyUUID)
}

// GetSimulationRun mocks base method.
func (m *MockAgentPlatformService) GetSimulationRun(runUUID string) (*do.SimulationRunDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulationRun", runUUID)
	ret0, _ := ret[0].(*do.SimulationRunDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulationRun indicates an expected call of GetSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) GetSimulationRun(runUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).GetSimulationRun), runUUID)
}

// ListAgentsByOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) ListAgentsByOpenAIAPIKey(openaiApiKeyId string) (do.Agents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(do.Agents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentsByOpenAIAPIKey indicates an expected call of ListAgentsByOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) ListAgentsByOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAgentsByOpenAIAPIKey), openaiApiKeyId)
}

// ListAvailableModels mocks base method.
func (m *MockAgentPlatformService) ListAvailableModels() (do.Models, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableModels")
	ret0, _ := ret[0].(do.Models)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableModels indicates an expected call of ListAvailableModels.
func (mr *MockAgentPlatformServiceMockRecorder) ListAvailableModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableModels", reflect.TypeOf((*MockAgentPlatformService)(nil).ListAvailableModels))
}

// ListDatacenterRegions mocks base method.
func (m *MockAgentPlatformService) ListDatacenterRegions(servesInference, servesBatch *bool) (do.DatacenterRegions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatacenterRegions", servesInference, servesBatch)
	ret0, _ := ret[0].(do.DatacenterRegions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatacenterRegions indicates an expected call of ListDatacenterRegions.
func (mr *MockAgentPlatformServiceMockRecorder) ListDatacenterRegions(servesInference, servesBatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatacenterRegions", reflect.TypeOf((*MockAgentPlatformService)(nil).ListDatacenterRegions), servesInference, servesBatch)
}

// ListEvaluationDatasets mocks base method.
func (m *MockGradientAIService) ListEvaluationDatasets(opt *godo.EvaluationDatasetListOptions) (do.EvaluationDatasets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvaluationDatasets", opt)
	ret0, _ := ret[0].(do.EvaluationDatasets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvaluationDatasets indicates an expected call of ListEvaluationDatasets.
func (mr *MockGradientAIServiceMockRecorder) ListEvaluationDatasets(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvaluationDatasets", reflect.TypeOf((*MockGradientAIService)(nil).ListEvaluationDatasets), opt)
}

// ListIndexingJobDataSources mocks base method.
func (m *MockAgentPlatformService) ListIndexingJobDataSources(indexingJobID string) (do.IndexingJobDataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobDataSources", indexingJobID)
	ret0, _ := ret[0].(do.IndexingJobDataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexingJobDataSources indicates an expected call of ListIndexingJobDataSources.
func (mr *MockAgentPlatformServiceMockRecorder) ListIndexingJobDataSources(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobDataSources", reflect.TypeOf((*MockAgentPlatformService)(nil).ListIndexingJobDataSources), indexingJobID)
}

// ListIndexingJobs mocks base method.
func (m *MockAgentPlatformService) ListIndexingJobs() (do.IndexingJobs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobs")
	ret0, _ := ret[0].(do.IndexingJobs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexingJobs indicates an expected call of ListIndexingJobs.
func (mr *MockAgentPlatformServiceMockRecorder) ListIndexingJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobs", reflect.TypeOf((*MockAgentPlatformService)(nil).ListIndexingJobs))
}

// ListKnowledgeBaseDataSources mocks base method.
func (m *MockAgentPlatformService) ListKnowledgeBaseDataSources(knowledgeBaseID string) (do.KnowledgeBaseDataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBaseDataSources", knowledgeBaseID)
	ret0, _ := ret[0].(do.KnowledgeBaseDataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBaseDataSources indicates an expected call of ListKnowledgeBaseDataSources.
func (mr *MockAgentPlatformServiceMockRecorder) ListKnowledgeBaseDataSources(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBaseDataSources", reflect.TypeOf((*MockAgentPlatformService)(nil).ListKnowledgeBaseDataSources), knowledgeBaseID)
}

// ListKnowledgeBases mocks base method.
func (m *MockAgentPlatformService) ListKnowledgeBases() (do.KnowledgeBases, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBases")
	ret0, _ := ret[0].(do.KnowledgeBases)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBases indicates an expected call of ListKnowledgeBases.
func (mr *MockAgentPlatformServiceMockRecorder) ListKnowledgeBases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBases", reflect.TypeOf((*MockAgentPlatformService)(nil).ListKnowledgeBases))
}

// ListModelEvaluationMetrics mocks base method.
func (m *MockGradientAIService) ListModelEvaluationMetrics() (do.EvaluationMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationMetrics")
	ret0, _ := ret[0].(do.EvaluationMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelEvaluationMetrics indicates an expected call of ListModelEvaluationMetrics.
func (mr *MockGradientAIServiceMockRecorder) ListModelEvaluationMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationMetrics", reflect.TypeOf((*MockGradientAIService)(nil).ListModelEvaluationMetrics))
}

// ListModelEvaluationPresets mocks base method.
func (m *MockGradientAIService) ListModelEvaluationPresets() (do.ModelEvaluationPresets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationPresets")
	ret0, _ := ret[0].(do.ModelEvaluationPresets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelEvaluationPresets indicates an expected call of ListModelEvaluationPresets.
func (mr *MockGradientAIServiceMockRecorder) ListModelEvaluationPresets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationPresets", reflect.TypeOf((*MockGradientAIService)(nil).ListModelEvaluationPresets))
}

// ListModelEvaluationRuns mocks base method.
func (m *MockGradientAIService) ListModelEvaluationRuns(opt *godo.ModelEvaluationRunListOptions) (do.ModelEvaluationRuns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelEvaluationRuns", opt)
	ret0, _ := ret[0].(do.ModelEvaluationRuns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelEvaluationRuns indicates an expected call of ListModelEvaluationRuns.
func (mr *MockGradientAIServiceMockRecorder) ListModelEvaluationRuns(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelEvaluationRuns", reflect.TypeOf((*MockGradientAIService)(nil).ListModelEvaluationRuns), opt)
}

// ListOpenAIAPIKeys mocks base method.
func (m *MockAgentPlatformService) ListOpenAIAPIKeys() (do.OpenAiApiKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenAIAPIKeys")
	ret0, _ := ret[0].(do.OpenAiApiKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenAIAPIKeys indicates an expected call of ListOpenAIAPIKeys.
func (mr *MockAgentPlatformServiceMockRecorder) ListOpenAIAPIKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenAIAPIKeys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListOpenAIAPIKeys))
}

// ListScenarioLibrary mocks base method.
func (m *MockAgentPlatformService) ListScenarioLibrary(opt *godo.ScenarioLibraryListOptions) (do.ScenarioLibraryEntries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioLibrary", opt)
	ret0, _ := ret[0].(do.ScenarioLibraryEntries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScenarioLibrary indicates an expected call of ListScenarioLibrary.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioLibrary(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioLibrary", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioLibrary), opt)
}

// ListScenarioLibraryScenarios mocks base method.
func (m *MockAgentPlatformService) ListScenarioLibraryScenarios(libraryScenarioUUID string, opt *godo.ScenarioListOptions) (do.Scenarios, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioLibraryScenarios", libraryScenarioUUID, opt)
	ret0, _ := ret[0].(do.Scenarios)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScenarioLibraryScenarios indicates an expected call of ListScenarioLibraryScenarios.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioLibraryScenarios(libraryScenarioUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioLibraryScenarios", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioLibraryScenarios), libraryScenarioUUID, opt)
}

// ListScenarioSets mocks base method.
func (m *MockAgentPlatformService) ListScenarioSets(opt *godo.ScenarioSetListOptions) (do.ScenarioSets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarioSets", opt)
	ret0, _ := ret[0].(do.ScenarioSets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScenarioSets indicates an expected call of ListScenarioSets.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarioSets(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarioSets", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarioSets), opt)
}

// ListScenarios mocks base method.
func (m *MockAgentPlatformService) ListScenarios(scenarioSetUUID string, opt *godo.ScenarioListOptions) (do.Scenarios, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarios", scenarioSetUUID, opt)
	ret0, _ := ret[0].(do.Scenarios)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScenarios indicates an expected call of ListScenarios.
func (mr *MockAgentPlatformServiceMockRecorder) ListScenarios(scenarioSetUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarios", reflect.TypeOf((*MockAgentPlatformService)(nil).ListScenarios), scenarioSetUUID, opt)
}

// ListSimulationJourneys mocks base method.
func (m *MockAgentPlatformService) ListSimulationJourneys(runUUID string, opt *godo.SimulationJourneyListOptions) (do.SimulationJourneys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationJourneys", runUUID, opt)
	ret0, _ := ret[0].(do.SimulationJourneys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulationJourneys indicates an expected call of ListSimulationJourneys.
func (mr *MockAgentPlatformServiceMockRecorder) ListSimulationJourneys(runUUID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationJourneys", reflect.TypeOf((*MockAgentPlatformService)(nil).ListSimulationJourneys), runUUID, opt)
}

// ListSimulationRuns mocks base method.
func (m *MockAgentPlatformService) ListSimulationRuns(opt *godo.SimulationRunListOptions) (do.SimulationRuns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationRuns", opt)
	ret0, _ := ret[0].(do.SimulationRuns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulationRuns indicates an expected call of ListSimulationRuns.
func (mr *MockAgentPlatformServiceMockRecorder) ListSimulationRuns(opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationRuns", reflect.TypeOf((*MockAgentPlatformService)(nil).ListSimulationRuns), opt)
}

// UpdateCustomEvaluationMetric mocks base method.
func (m *MockGradientAIService) UpdateCustomEvaluationMetric(metricUUID string, req *godo.UpdateCustomEvaluationMetricRequest) (*do.EvaluationMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomEvaluationMetric", metricUUID, req)
	ret0, _ := ret[0].(*do.EvaluationMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomEvaluationMetric indicates an expected call of UpdateCustomEvaluationMetric.
func (mr *MockGradientAIServiceMockRecorder) UpdateCustomEvaluationMetric(metricUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomEvaluationMetric", reflect.TypeOf((*MockGradientAIService)(nil).UpdateCustomEvaluationMetric), metricUUID, req)
}

// UpdateKnowledgeBase mocks base method.
func (m *MockAgentPlatformService) UpdateKnowledgeBase(knowledgeBaseID string, req *godo.UpdateKnowledgeBaseRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateKnowledgeBase(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateKnowledgeBase), knowledgeBaseID, req)
}

// UpdateModelEvaluationRun mocks base method.
func (m *MockGradientAIService) UpdateModelEvaluationRun(evalRunUUID string, req *godo.UpdateModelEvaluationRunRequest) (*do.ModelEvaluationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelEvaluationRun", evalRunUUID, req)
	ret0, _ := ret[0].(*do.ModelEvaluationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModelEvaluationRun indicates an expected call of UpdateModelEvaluationRun.
func (mr *MockGradientAIServiceMockRecorder) UpdateModelEvaluationRun(evalRunUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelEvaluationRun", reflect.TypeOf((*MockGradientAIService)(nil).UpdateModelEvaluationRun), evalRunUUID, req)
}

// UpdateOpenAIAPIKey mocks base method.
func (m *MockAgentPlatformService) UpdateOpenAIAPIKey(openaiApiKeyId string, openaiAPIKeyUpdate *godo.OpenAIAPIKeyUpdateRequest) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpenAIAPIKey", openaiApiKeyId, openaiAPIKeyUpdate)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOpenAIAPIKey indicates an expected call of UpdateOpenAIAPIKey.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateOpenAIAPIKey(openaiApiKeyId, openaiAPIKeyUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpenAIAPIKey", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateOpenAIAPIKey), openaiApiKeyId, openaiAPIKeyUpdate)
}

// UpdateScenarioSet mocks base method.
func (m *MockAgentPlatformService) UpdateScenarioSet(scenarioSetUUID string, req *godo.UpdateScenarioSetRequest) (*do.ScenarioSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScenarioSet", scenarioSetUUID, req)
	ret0, _ := ret[0].(*do.ScenarioSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScenarioSet indicates an expected call of UpdateScenarioSet.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateScenarioSet(scenarioSetUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScenarioSet", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateScenarioSet), scenarioSetUUID, req)
}

// UpdateSimulationRun mocks base method.
func (m *MockAgentPlatformService) UpdateSimulationRun(runUUID string, req *godo.UpdateSimulationRunRequest) (*do.SimulationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSimulationRun", runUUID, req)
	ret0, _ := ret[0].(*do.SimulationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSimulationRun indicates an expected call of UpdateSimulationRun.
func (mr *MockAgentPlatformServiceMockRecorder) UpdateSimulationRun(runUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSimulationRun", reflect.TypeOf((*MockAgentPlatformService)(nil).UpdateSimulationRun), runUUID, req)
}
