// Code generated by MockGen. DO NOT EDIT.
// Source: apps.go
//
// Generated by this command:
//
//	mockgen -source apps.go -package=mocks AppsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockAppsService is a mock of AppsService interface.
type MockAppsService struct {
	ctrl     *gomock.Controller
	recorder *MockAppsServiceMockRecorder
	isgomock struct{}
}

// MockAppsServiceMockRecorder is the mock recorder for MockAppsService.
type MockAppsServiceMockRecorder struct {
	mock *MockAppsService
}

// NewMockAppsService creates a new mock instance.
func NewMockAppsService(ctrl *gomock.Controller) *MockAppsService {
	mock := &MockAppsService{ctrl: ctrl}
	mock.recorder = &MockAppsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppsService) EXPECT() *MockAppsServiceMockRecorder {
	return m.recorder
}

// CancelJobInvocation mocks base method.
func (m *MockAppsService) CancelJobInvocation(appID, jobInvocationID string, opts *godo.CancelJobInvocationOptions) (*godo.JobInvocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJobInvocation", appID, jobInvocationID, opts)
	ret0, _ := ret[0].(*godo.JobInvocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelJobInvocation indicates an expected call of CancelJobInvocation.
func (mr *MockAppsServiceMockRecorder) CancelJobInvocation(appID, jobInvocationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJobInvocation", reflect.TypeOf((*MockAppsService)(nil).CancelJobInvocation), appID, jobInvocationID, opts)
}

// Create mocks base method.
func (m *MockAppsService) Create(req *godo.AppCreateRequest) (*godo.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*godo.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAppsServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppsService)(nil).Create), req)
}

// CreateDeployment mocks base method.
func (m *MockAppsService) CreateDeployment(appID string, forceRebuild bool) (*godo.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeployment", appID, forceRebuild)
	ret0, _ := ret[0].(*godo.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeployment indicates an expected call of CreateDeployment.
func (mr *MockAppsServiceMockRecorder) CreateDeployment(appID, forceRebuild any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeployment", reflect.TypeOf((*MockAppsService)(nil).CreateDeployment), appID, forceRebuild)
}

// Delete mocks base method.
func (m *MockAppsService) Delete(appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAppsServiceMockRecorder) Delete(appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAppsService)(nil).Delete), appID)
}

// Find mocks base method.
func (m *MockAppsService) Find(appRef string) (*godo.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", appRef)
	ret0, _ := ret[0].(*godo.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAppsServiceMockRecorder) Find(appRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAppsService)(nil).Find), appRef)
}

// Get mocks base method.
func (m *MockAppsService) Get(appID string) (*godo.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", appID)
	ret0, _ := ret[0].(*godo.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppsServiceMockRecorder) Get(appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppsService)(nil).Get), appID)
}

// GetAppInstances mocks base method.
func (m *MockAppsService) GetAppInstances(appID string, opts *godo.GetAppInstancesOpts) ([]*godo.AppInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppInstances", appID, opts)
	ret0, _ := ret[0].([]*godo.AppInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppInstances indicates an expected call of GetAppInstances.
func (mr *MockAppsServiceMockRecorder) GetAppInstances(appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppInstances", reflect.TypeOf((*MockAppsService)(nil).GetAppInstances), appID, opts)
}

// GetDeployment mocks base method.
func (m *MockAppsService) GetDeployment(appID, deploymentID string) (*godo.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployment", appID, deploymentID)
	ret0, _ := ret[0].(*godo.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployment indicates an expected call of GetDeployment.
func (mr *MockAppsServiceMockRecorder) GetDeployment(appID, deploymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployment", reflect.TypeOf((*MockAppsService)(nil).GetDeployment), appID, deploymentID)
}

// GetExec mocks base method.
func (m *MockAppsService) GetExec(appID, deploymentID, componentName string) (*godo.AppExec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExec", appID, deploymentID, componentName)
	ret0, _ := ret[0].(*godo.AppExec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExec indicates an expected call of GetExec.
func (mr *MockAppsServiceMockRecorder) GetExec(appID, deploymentID, componentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExec", reflect.TypeOf((*MockAppsService)(nil).GetExec), appID, deploymentID, componentName)
}

// GetExecWithOpts mocks base method.
func (m *MockAppsService) GetExecWithOpts(appID, componentName string, opts *godo.AppGetExecOptions) (*godo.AppExec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecWithOpts", appID, componentName, opts)
	ret0, _ := ret[0].(*godo.AppExec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecWithOpts indicates an expected call of GetExecWithOpts.
func (mr *MockAppsServiceMockRecorder) GetExecWithOpts(appID, componentName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecWithOpts", reflect.TypeOf((*MockAppsService)(nil).GetExecWithOpts), appID, componentName, opts)
}

// GetInstanceSize mocks base method.
func (m *MockAppsService) GetInstanceSize(slug string) (*godo.AppInstanceSize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceSize", slug)
	ret0, _ := ret[0].(*godo.AppInstanceSize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceSize indicates an expected call of GetInstanceSize.
func (mr *MockAppsServiceMockRecorder) GetInstanceSize(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceSize", reflect.TypeOf((*MockAppsService)(nil).GetInstanceSize), slug)
}

// GetJobInvocation mocks base method.
func (m *MockAppsService) GetJobInvocation(appID, jobInvocationID string, opts *godo.GetJobInvocationOptions) (*godo.JobInvocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobInvocation", appID, jobInvocationID, opts)
	ret0, _ := ret[0].(*godo.JobInvocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobInvocation indicates an expected call of GetJobInvocation.
func (mr *MockAppsServiceMockRecorder) GetJobInvocation(appID, jobInvocationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobInvocation", reflect.TypeOf((*MockAppsService)(nil).GetJobInvocation), appID, jobInvocationID, opts)
}

// GetJobInvocationLogs mocks base method.
func (m *MockAppsService) GetJobInvocationLogs(appID, jobInvocationID string, opts *godo.GetJobInvocationLogsOptions) (*godo.AppLogs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobInvocationLogs", appID, jobInvocationID, opts)
	ret0, _ := ret[0].(*godo.AppLogs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobInvocationLogs indicates an expected call of GetJobInvocationLogs.
func (mr *MockAppsServiceMockRecorder) GetJobInvocationLogs(appID, jobInvocationID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobInvocationLogs", reflect.TypeOf((*MockAppsService)(nil).GetJobInvocationLogs), appID, jobInvocationID, opts)
}

// GetLogs mocks base method.
func (m *MockAppsService) GetLogs(appID, deploymentID, component string, logType godo.AppLogType, follow bool, tail int) (*godo.AppLogs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", appID, deploymentID, component, logType, follow, tail)
	ret0, _ := ret[0].(*godo.AppLogs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAppsServiceMockRecorder) GetLogs(appID, deploymentID, component, logType, follow, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAppsService)(nil).GetLogs), appID, deploymentID, component, logType, follow, tail)
}

// GetTier mocks base method.
func (m *MockAppsService) GetTier(slug string) (*godo.AppTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTier", slug)
	ret0, _ := ret[0].(*godo.AppTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTier indicates an expected call of GetTier.
func (mr *MockAppsServiceMockRecorder) GetTier(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTier", reflect.TypeOf((*MockAppsService)(nil).GetTier), slug)
}

// List mocks base method.
func (m *MockAppsService) List(withProjects bool) ([]*godo.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", withProjects)
	ret0, _ := ret[0].([]*godo.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAppsServiceMockRecorder) List(withProjects any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAppsService)(nil).List), withProjects)
}

// ListAlerts mocks base method.
func (m *MockAppsService) ListAlerts(appID string) ([]*godo.AppAlert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlerts", appID)
	ret0, _ := ret[0].([]*godo.AppAlert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlerts indicates an expected call of ListAlerts.
func (mr *MockAppsServiceMockRecorder) ListAlerts(appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlerts", reflect.TypeOf((*MockAppsService)(nil).ListAlerts), appID)
}

// ListBuildpacks mocks base method.
func (m *MockAppsService) ListBuildpacks() ([]*godo.Buildpack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuildpacks")
	ret0, _ := ret[0].([]*godo.Buildpack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuildpacks indicates an expected call of ListBuildpacks.
func (mr *MockAppsServiceMockRecorder) ListBuildpacks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuildpacks", reflect.TypeOf((*MockAppsService)(nil).ListBuildpacks))
}

// ListDeployments mocks base method.
func (m *MockAppsService) ListDeployments(appID string) ([]*godo.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeployments", appID)
	ret0, _ := ret[0].([]*godo.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeployments indicates an expected call of ListDeployments.
func (mr *MockAppsServiceMockRecorder) ListDeployments(appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeployments", reflect.TypeOf((*MockAppsService)(nil).ListDeployments), appID)
}

// ListInstanceSizes mocks base method.
func (m *MockAppsService) ListInstanceSizes() ([]*godo.AppInstanceSize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceSizes")
	ret0, _ := ret[0].([]*godo.AppInstanceSize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceSizes indicates an expected call of ListInstanceSizes.
func (mr *MockAppsServiceMockRecorder) ListInstanceSizes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceSizes", reflect.TypeOf((*MockAppsService)(nil).ListInstanceSizes))
}

// ListJobInvocations mocks base method.
func (m *MockAppsService) ListJobInvocations(appID string, opts *godo.ListJobInvocationsOptions) ([]*godo.JobInvocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobInvocations", appID, opts)
	ret0, _ := ret[0].([]*godo.JobInvocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobInvocations indicates an expected call of ListJobInvocations.
func (mr *MockAppsServiceMockRecorder) ListJobInvocations(appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobInvocations", reflect.TypeOf((*MockAppsService)(nil).ListJobInvocations), appID, opts)
}

// ListRegions mocks base method.
func (m *MockAppsService) ListRegions() ([]*godo.AppRegion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions")
	ret0, _ := ret[0].([]*godo.AppRegion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockAppsServiceMockRecorder) ListRegions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockAppsService)(nil).ListRegions))
}

// ListTiers mocks base method.
func (m *MockAppsService) ListTiers() ([]*godo.AppTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTiers")
	ret0, _ := ret[0].([]*godo.AppTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTiers indicates an expected call of ListTiers.
func (mr *MockAppsServiceMockRecorder) ListTiers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTiers", reflect.TypeOf((*MockAppsService)(nil).ListTiers))
}

// Propose mocks base method.
func (m *MockAppsService) Propose(req *godo.AppProposeRequest) (*godo.AppProposeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Propose", req)
	ret0, _ := ret[0].(*godo.AppProposeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Propose indicates an expected call of Propose.
func (mr *MockAppsServiceMockRecorder) Propose(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Propose", reflect.TypeOf((*MockAppsService)(nil).Propose), req)
}

// Restart mocks base method.
func (m *MockAppsService) Restart(appID string, components []string) (*godo.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", appID, components)
	ret0, _ := ret[0].(*godo.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockAppsServiceMockRecorder) Restart(appID, components any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockAppsService)(nil).Restart), appID, components)
}

// Update mocks base method.
func (m *MockAppsService) Update(appID string, req *godo.AppUpdateRequest) (*godo.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", appID, req)
	ret0, _ := ret[0].(*godo.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAppsServiceMockRecorder) Update(appID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAppsService)(nil).Update), appID, req)
}

// UpdateAlertDestinations mocks base method.
func (m *MockAppsService) UpdateAlertDestinations(appID, alertID string, update *godo.AlertDestinationUpdateRequest) (*godo.AppAlert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlertDestinations", appID, alertID, update)
	ret0, _ := ret[0].(*godo.AppAlert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlertDestinations indicates an expected call of UpdateAlertDestinations.
func (mr *MockAppsServiceMockRecorder) UpdateAlertDestinations(appID, alertID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlertDestinations", reflect.TypeOf((*MockAppsService)(nil).UpdateAlertDestinations), appID, alertID, update)
}

// UpgradeBuildpack mocks base method.
func (m *MockAppsService) UpgradeBuildpack(appID string, options godo.UpgradeBuildpackOptions) ([]string, *godo.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeBuildpack", appID, options)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*godo.Deployment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpgradeBuildpack indicates an expected call of UpgradeBuildpack.
func (mr *MockAppsServiceMockRecorder) UpgradeBuildpack(appID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeBuildpack", reflect.TypeOf((*MockAppsService)(nil).UpgradeBuildpack), appID, options)
}
