// Code generated by MockGen. DO NOT EDIT.
// Source: genai.go
//
// Generated by this command:
//
//	mockgen -source genai.go -package=mocks GenAIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockGenAIService is a mock of GenAIService interface.
type MockGenAIService struct {
	ctrl     *gomock.Controller
	recorder *MockGenAIServiceMockRecorder
	isgomock struct{}
}

// MockGenAIServiceMockRecorder is the mock recorder for MockGenAIService.
type MockGenAIServiceMockRecorder struct {
	mock *MockGenAIService
}

// NewMockGenAIService creates a new mock instance.
func NewMockGenAIService(ctrl *gomock.Controller) *MockGenAIService {
	mock := &MockGenAIService{ctrl: ctrl}
	mock.recorder = &MockGenAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenAIService) EXPECT() *MockGenAIServiceMockRecorder {
	return m.recorder
}

// AddKnowledgeBaseDataSource mocks base method.
func (m *MockGenAIService) AddKnowledgeBaseDataSource(knowledgeBaseID string, req *godo.AddDataSourceRequest) (*do.KnowledgeBaseDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledgeBaseDataSource", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKnowledgeBaseDataSource indicates an expected call of AddKnowledgeBaseDataSource.
func (mr *MockGenAIServiceMockRecorder) AddKnowledgeBaseDataSource(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledgeBaseDataSource", reflect.TypeOf((*MockGenAIService)(nil).AddKnowledgeBaseDataSource), knowledgeBaseID, req)
}

// AttachKnowledgebase mocks base method.
func (m *MockGenAIService) AttachKnowledgebase(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachKnowledgebase", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachKnowledgebase indicates an expected call of AttachKnowledgebase.
func (mr *MockGenAIServiceMockRecorder) AttachKnowledgebase(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachKnowledgebase", reflect.TypeOf((*MockGenAIService)(nil).AttachKnowledgebase), agentId, knowledgeBaseID)
}

// CreateKnowledgeBase mocks base method.
func (m *MockGenAIService) CreateKnowledgeBase(req *godo.KnowledgeBaseCreateRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockGenAIServiceMockRecorder) CreateKnowledgeBase(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockGenAIService)(nil).CreateKnowledgeBase), req)
}

// DeleteKnowledgeBaseDataSource mocks base method.
func (m *MockGenAIService) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBaseDataSource", knowledgeBaseID, dataSourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeBaseDataSource indicates an expected call of DeleteKnowledgeBaseDataSource.
func (mr *MockGenAIServiceMockRecorder) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBaseDataSource", reflect.TypeOf((*MockGenAIService)(nil).DeleteKnowledgeBaseDataSource), knowledgeBaseID, dataSourceID)
}

// DeleteKnowledgebase mocks base method.
func (m *MockGenAIService) DeleteKnowledgebase(knowledgeBaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgebase", knowledgeBaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgebase indicates an expected call of DeleteKnowledgebase.
func (mr *MockGenAIServiceMockRecorder) DeleteKnowledgebase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgebase", reflect.TypeOf((*MockGenAIService)(nil).DeleteKnowledgebase), knowledgeBaseID)
}

// DetachKnowledgebase mocks base method.
func (m *MockGenAIService) DetachKnowledgebase(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachKnowledgebase", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachKnowledgebase indicates an expected call of DetachKnowledgebase.
func (mr *MockGenAIServiceMockRecorder) DetachKnowledgebase(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachKnowledgebase", reflect.TypeOf((*MockGenAIService)(nil).DetachKnowledgebase), agentId, knowledgeBaseID)
}

// GetKnowledgeBase mocks base method.
func (m *MockGenAIService) GetKnowledgeBase(knowledgeBaseID string) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", knowledgeBaseID)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockGenAIServiceMockRecorder) GetKnowledgeBase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockGenAIService)(nil).GetKnowledgeBase), knowledgeBaseID)
}

// ListKnowledgeBaseDataSources mocks base method.
func (m *MockGenAIService) ListKnowledgeBaseDataSources(knowledgeBaseID string) (do.KnowledgeBaseDataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBaseDataSources", knowledgeBaseID)
	ret0, _ := ret[0].(do.KnowledgeBaseDataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBaseDataSources indicates an expected call of ListKnowledgeBaseDataSources.
func (mr *MockGenAIServiceMockRecorder) ListKnowledgeBaseDataSources(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBaseDataSources", reflect.TypeOf((*MockGenAIService)(nil).ListKnowledgeBaseDataSources), knowledgeBaseID)
}

// ListKnowledgeBases mocks base method.
func (m *MockGenAIService) ListKnowledgeBases() (do.KnowledgeBases, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBases")
	ret0, _ := ret[0].(do.KnowledgeBases)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBases indicates an expected call of ListKnowledgeBases.
func (mr *MockGenAIServiceMockRecorder) ListKnowledgeBases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBases", reflect.TypeOf((*MockGenAIService)(nil).ListKnowledgeBases))
}

// UpdateKnowledgebase mocks base method.
func (m *MockGenAIService) UpdateKnowledgebase(knowledgeBaseID string, req *godo.UpdateKnowledgeBaseRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgebase", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKnowledgebase indicates an expected call of UpdateKnowledgebase.
func (mr *MockGenAIServiceMockRecorder) UpdateKnowledgebase(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgebase", reflect.TypeOf((*MockGenAIService)(nil).UpdateKnowledgebase), knowledgeBaseID, req)
}
