// Code generated by MockGen. DO NOT EDIT.
// Source: gradientai.go
//
// Generated by this command:
//
//	mockgen -source gradientai.go -package=mocks GradientAIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockGradientAIService is a mock of GradientAIService interface.
type MockGradientAIService struct {
	ctrl     *gomock.Controller
	recorder *MockGradientAIServiceMockRecorder
	isgomock struct{}
}

// MockGradientAIServiceMockRecorder is the mock recorder for MockGradientAIService.
type MockGradientAIServiceMockRecorder struct {
	mock *MockGradientAIService
}

// NewMockGradientAIService creates a new mock instance.
func NewMockGradientAIService(ctrl *gomock.Controller) *MockGradientAIService {
	mock := &MockGradientAIService{ctrl: ctrl}
	mock.recorder = &MockGradientAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradientAIService) EXPECT() *MockGradientAIServiceMockRecorder {
	return m.recorder
}

// AddKnowledgeBaseDataSource mocks base method.
func (m *MockGradientAIService) AddKnowledgeBaseDataSource(knowledgeBaseID string, req *godo.AddKnowledgeBaseDataSourceRequest) (*do.KnowledgeBaseDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledgeBaseDataSource", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBaseDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddKnowledgeBaseDataSource indicates an expected call of AddKnowledgeBaseDataSource.
func (mr *MockGradientAIServiceMockRecorder) AddKnowledgeBaseDataSource(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledgeBaseDataSource", reflect.TypeOf((*MockGradientAIService)(nil).AddKnowledgeBaseDataSource), knowledgeBaseID, req)
}

// AttachKnowledgeBaseToAgent mocks base method.
func (m *MockGradientAIService) AttachKnowledgeBaseToAgent(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachKnowledgeBaseToAgent", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachKnowledgeBaseToAgent indicates an expected call of AttachKnowledgeBaseToAgent.
func (mr *MockGradientAIServiceMockRecorder) AttachKnowledgeBaseToAgent(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachKnowledgeBaseToAgent", reflect.TypeOf((*MockGradientAIService)(nil).AttachKnowledgeBaseToAgent), agentId, knowledgeBaseID)
}

// CancelIndexingJob mocks base method.
func (m *MockGradientAIService) CancelIndexingJob(indexingJobID string) (*do.IndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIndexingJob", indexingJobID)
	ret0, _ := ret[0].(*do.IndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelIndexingJob indicates an expected call of CancelIndexingJob.
func (mr *MockGradientAIServiceMockRecorder) CancelIndexingJob(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIndexingJob", reflect.TypeOf((*MockGradientAIService)(nil).CancelIndexingJob), indexingJobID)
}

// CreateKnowledgeBase mocks base method.
func (m *MockGradientAIService) CreateKnowledgeBase(req *godo.KnowledgeBaseCreateRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnowledgeBase", req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnowledgeBase indicates an expected call of CreateKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) CreateKnowledgeBase(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).CreateKnowledgeBase), req)
}

// CreateOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) CreateOpenAIAPIKey(openaiAPIKeyCreate *godo.OpenAIAPIKeyCreateRequest) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenAIAPIKey", openaiAPIKeyCreate)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOpenAIAPIKey indicates an expected call of CreateOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) CreateOpenAIAPIKey(openaiAPIKeyCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).CreateOpenAIAPIKey), openaiAPIKeyCreate)
}

// DeleteKnowledgeBase mocks base method.
func (m *MockGradientAIService) DeleteKnowledgeBase(knowledgeBaseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBase", knowledgeBaseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeBase indicates an expected call of DeleteKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) DeleteKnowledgeBase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).DeleteKnowledgeBase), knowledgeBaseID)
}

// DeleteKnowledgeBaseDataSource mocks base method.
func (m *MockGradientAIService) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgeBaseDataSource", knowledgeBaseID, dataSourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKnowledgeBaseDataSource indicates an expected call of DeleteKnowledgeBaseDataSource.
func (mr *MockGradientAIServiceMockRecorder) DeleteKnowledgeBaseDataSource(knowledgeBaseID, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgeBaseDataSource", reflect.TypeOf((*MockGradientAIService)(nil).DeleteKnowledgeBaseDataSource), knowledgeBaseID, dataSourceID)
}

// DeleteOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) DeleteOpenAIAPIKey(openaiApiKeyId string) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOpenAIAPIKey indicates an expected call of DeleteOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) DeleteOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).DeleteOpenAIAPIKey), openaiApiKeyId)
}

// DetachKnowledgeBaseToAgent mocks base method.
func (m *MockGradientAIService) DetachKnowledgeBaseToAgent(agentId, knowledgeBaseID string) (*do.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachKnowledgeBaseToAgent", agentId, knowledgeBaseID)
	ret0, _ := ret[0].(*do.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachKnowledgeBaseToAgent indicates an expected call of DetachKnowledgeBaseToAgent.
func (mr *MockGradientAIServiceMockRecorder) DetachKnowledgeBaseToAgent(agentId, knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachKnowledgeBaseToAgent", reflect.TypeOf((*MockGradientAIService)(nil).DetachKnowledgeBaseToAgent), agentId, knowledgeBaseID)
}

// GetIndexingJob mocks base method.
func (m *MockGradientAIService) GetIndexingJob(indexingJobID string) (*do.IndexingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexingJob", indexingJobID)
	ret0, _ := ret[0].(*do.IndexingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexingJob indicates an expected call of GetIndexingJob.
func (mr *MockGradientAIServiceMockRecorder) GetIndexingJob(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexingJob", reflect.TypeOf((*MockGradientAIService)(nil).GetIndexingJob), indexingJobID)
}

// GetKnowledgeBase mocks base method.
func (m *MockGradientAIService) GetKnowledgeBase(knowledgeBaseID string) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", knowledgeBaseID)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) GetKnowledgeBase(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).GetKnowledgeBase), knowledgeBaseID)
}

// GetOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) GetOpenAIAPIKey(openaiApiKeyId string) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenAIAPIKey indicates an expected call of GetOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) GetOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).GetOpenAIAPIKey), openaiApiKeyId)
}

// ListAgentsByOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) ListAgentsByOpenAIAPIKey(openaiApiKeyId string) (do.Agents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByOpenAIAPIKey", openaiApiKeyId)
	ret0, _ := ret[0].(do.Agents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentsByOpenAIAPIKey indicates an expected call of ListAgentsByOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) ListAgentsByOpenAIAPIKey(openaiApiKeyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).ListAgentsByOpenAIAPIKey), openaiApiKeyId)
}

// ListAvailableModels mocks base method.
func (m *MockGradientAIService) ListAvailableModels() (do.Models, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableModels")
	ret0, _ := ret[0].(do.Models)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableModels indicates an expected call of ListAvailableModels.
func (mr *MockGradientAIServiceMockRecorder) ListAvailableModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableModels", reflect.TypeOf((*MockGradientAIService)(nil).ListAvailableModels))
}

// ListDatacenterRegions mocks base method.
func (m *MockGradientAIService) ListDatacenterRegions(servesInference, servesBatch *bool) (do.DatacenterRegions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatacenterRegions", servesInference, servesBatch)
	ret0, _ := ret[0].(do.DatacenterRegions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatacenterRegions indicates an expected call of ListDatacenterRegions.
func (mr *MockGradientAIServiceMockRecorder) ListDatacenterRegions(servesInference, servesBatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatacenterRegions", reflect.TypeOf((*MockGradientAIService)(nil).ListDatacenterRegions), servesInference, servesBatch)
}

// ListIndexingJobDataSources mocks base method.
func (m *MockGradientAIService) ListIndexingJobDataSources(indexingJobID string) (do.IndexingJobDataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobDataSources", indexingJobID)
	ret0, _ := ret[0].(do.IndexingJobDataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexingJobDataSources indicates an expected call of ListIndexingJobDataSources.
func (mr *MockGradientAIServiceMockRecorder) ListIndexingJobDataSources(indexingJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobDataSources", reflect.TypeOf((*MockGradientAIService)(nil).ListIndexingJobDataSources), indexingJobID)
}

// ListIndexingJobs mocks base method.
func (m *MockGradientAIService) ListIndexingJobs() (do.IndexingJobs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexingJobs")
	ret0, _ := ret[0].(do.IndexingJobs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexingJobs indicates an expected call of ListIndexingJobs.
func (mr *MockGradientAIServiceMockRecorder) ListIndexingJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexingJobs", reflect.TypeOf((*MockGradientAIService)(nil).ListIndexingJobs))
}

// ListKnowledgeBaseDataSources mocks base method.
func (m *MockGradientAIService) ListKnowledgeBaseDataSources(knowledgeBaseID string) (do.KnowledgeBaseDataSources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBaseDataSources", knowledgeBaseID)
	ret0, _ := ret[0].(do.KnowledgeBaseDataSources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBaseDataSources indicates an expected call of ListKnowledgeBaseDataSources.
func (mr *MockGradientAIServiceMockRecorder) ListKnowledgeBaseDataSources(knowledgeBaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBaseDataSources", reflect.TypeOf((*MockGradientAIService)(nil).ListKnowledgeBaseDataSources), knowledgeBaseID)
}

// ListKnowledgeBases mocks base method.
func (m *MockGradientAIService) ListKnowledgeBases() (do.KnowledgeBases, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeBases")
	ret0, _ := ret[0].(do.KnowledgeBases)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeBases indicates an expected call of ListKnowledgeBases.
func (mr *MockGradientAIServiceMockRecorder) ListKnowledgeBases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeBases", reflect.TypeOf((*MockGradientAIService)(nil).ListKnowledgeBases))
}

// ListOpenAIAPIKeys mocks base method.
func (m *MockGradientAIService) ListOpenAIAPIKeys() (do.OpenAiApiKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenAIAPIKeys")
	ret0, _ := ret[0].(do.OpenAiApiKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenAIAPIKeys indicates an expected call of ListOpenAIAPIKeys.
func (mr *MockGradientAIServiceMockRecorder) ListOpenAIAPIKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenAIAPIKeys", reflect.TypeOf((*MockGradientAIService)(nil).ListOpenAIAPIKeys))
}

// UpdateKnowledgeBase mocks base method.
func (m *MockGradientAIService) UpdateKnowledgeBase(knowledgeBaseID string, req *godo.UpdateKnowledgeBaseRequest) (*do.KnowledgeBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgeBase", knowledgeBaseID, req)
	ret0, _ := ret[0].(*do.KnowledgeBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKnowledgeBase indicates an expected call of UpdateKnowledgeBase.
func (mr *MockGradientAIServiceMockRecorder) UpdateKnowledgeBase(knowledgeBaseID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgeBase", reflect.TypeOf((*MockGradientAIService)(nil).UpdateKnowledgeBase), knowledgeBaseID, req)
}

// UpdateOpenAIAPIKey mocks base method.
func (m *MockGradientAIService) UpdateOpenAIAPIKey(openaiApiKeyId string, openaiAPIKeyUpdate *godo.OpenAIAPIKeyUpdateRequest) (*do.OpenAiApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOpenAIAPIKey", openaiApiKeyId, openaiAPIKeyUpdate)
	ret0, _ := ret[0].(*do.OpenAiApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOpenAIAPIKey indicates an expected call of UpdateOpenAIAPIKey.
func (mr *MockGradientAIServiceMockRecorder) UpdateOpenAIAPIKey(openaiApiKeyId, openaiAPIKeyUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOpenAIAPIKey", reflect.TypeOf((*MockGradientAIService)(nil).UpdateOpenAIAPIKey), openaiApiKeyId, openaiAPIKeyUpdate)
}
