// Code generated by MockGen. DO NOT EDIT.
// Source: do/agents.go
//
// Generated by this command:
//
//	mockgen -source do/agents.go -package=mocks -destination do/mocks/HostedAgentsService.go HostedAgentsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockHostedAgentsService is a mock of HostedAgentsService interface.
type MockHostedAgentsService struct {
	ctrl     *gomock.Controller
	recorder *MockHostedAgentsServiceMockRecorder
	isgomock struct{}
}

// MockHostedAgentsServiceMockRecorder is the mock recorder for MockHostedAgentsService.
type MockHostedAgentsServiceMockRecorder struct {
	mock *MockHostedAgentsService
}

// NewMockHostedAgentsService creates a new mock instance.
func NewMockHostedAgentsService(ctrl *gomock.Controller) *MockHostedAgentsService {
	mock := &MockHostedAgentsService{ctrl: ctrl}
	mock.recorder = &MockHostedAgentsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostedAgentsService) EXPECT() *MockHostedAgentsServiceMockRecorder {
	return m.recorder
}

// CancelWorkspaceTransfer mocks base method.
func (m *MockHostedAgentsService) CancelWorkspaceTransfer(sessionID, transferID string, input *godo.HostedAgentWorkspaceTransferCancelRequest) (*godo.HostedAgentWorkspaceTransferCancelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelWorkspaceTransfer", sessionID, transferID, input)
	ret0, _ := ret[0].(*godo.HostedAgentWorkspaceTransferCancelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelWorkspaceTransfer indicates an expected call of CancelWorkspaceTransfer.
func (mr *MockHostedAgentsServiceMockRecorder) CancelWorkspaceTransfer(sessionID, transferID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelWorkspaceTransfer", reflect.TypeOf((*MockHostedAgentsService)(nil).CancelWorkspaceTransfer), sessionID, transferID, input)
}

// CommitWorkspaceTransfer mocks base method.
func (m *MockHostedAgentsService) CommitWorkspaceTransfer(sessionID, transferID string, input *godo.HostedAgentWorkspaceTransferCommitRequest) (*godo.HostedAgentWorkspaceTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitWorkspaceTransfer", sessionID, transferID, input)
	ret0, _ := ret[0].(*godo.HostedAgentWorkspaceTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitWorkspaceTransfer indicates an expected call of CommitWorkspaceTransfer.
func (mr *MockHostedAgentsServiceMockRecorder) CommitWorkspaceTransfer(sessionID, transferID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitWorkspaceTransfer", reflect.TypeOf((*MockHostedAgentsService)(nil).CommitWorkspaceTransfer), sessionID, transferID, input)
}

// CreateCheckpoint mocks base method.
func (m *MockHostedAgentsService) CreateCheckpoint(sessionID string, create *godo.HostedAgentCheckpointCreateRequest) (*godo.HostedAgentCheckpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckpoint", sessionID, create)
	ret0, _ := ret[0].(*godo.HostedAgentCheckpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckpoint indicates an expected call of CreateCheckpoint.
func (mr *MockHostedAgentsServiceMockRecorder) CreateCheckpoint(sessionID, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckpoint", reflect.TypeOf((*MockHostedAgentsService)(nil).CreateCheckpoint), sessionID, create)
}

// CreateSessionFromManifest mocks base method.
func (m *MockHostedAgentsService) CreateSessionFromManifest(manifest []byte, opt *godo.HostedAgentManifestCreateOptions) (*do.HostedAgentSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionFromManifest", manifest, opt)
	ret0, _ := ret[0].(*do.HostedAgentSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionFromManifest indicates an expected call of CreateSessionFromManifest.
func (mr *MockHostedAgentsServiceMockRecorder) CreateSessionFromManifest(manifest, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionFromManifest", reflect.TypeOf((*MockHostedAgentsService)(nil).CreateSessionFromManifest), manifest, opt)
}

// CreateWorkspaceTransfer mocks base method.
func (m *MockHostedAgentsService) CreateWorkspaceTransfer(sessionID string, create *godo.HostedAgentWorkspaceTransferCreateRequest) (*godo.HostedAgentWorkspaceTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceTransfer", sessionID, create)
	ret0, _ := ret[0].(*godo.HostedAgentWorkspaceTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceTransfer indicates an expected call of CreateWorkspaceTransfer.
func (mr *MockHostedAgentsServiceMockRecorder) CreateWorkspaceTransfer(sessionID, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceTransfer", reflect.TypeOf((*MockHostedAgentsService)(nil).CreateWorkspaceTransfer), sessionID, create)
}

// CreateWorkspaceTransferPartUploadURLs mocks base method.
func (m *MockHostedAgentsService) CreateWorkspaceTransferPartUploadURLs(sessionID, transferID string, input *godo.HostedAgentWorkspaceTransferPartUploadURLsRequest) (*godo.HostedAgentWorkspaceTransferPartUploadURLs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceTransferPartUploadURLs", sessionID, transferID, input)
	ret0, _ := ret[0].(*godo.HostedAgentWorkspaceTransferPartUploadURLs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceTransferPartUploadURLs indicates an expected call of CreateWorkspaceTransferPartUploadURLs.
func (mr *MockHostedAgentsServiceMockRecorder) CreateWorkspaceTransferPartUploadURLs(sessionID, transferID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceTransferPartUploadURLs", reflect.TypeOf((*MockHostedAgentsService)(nil).CreateWorkspaceTransferPartUploadURLs), sessionID, transferID, input)
}

// DeleteCheckpoint mocks base method.
func (m *MockHostedAgentsService) DeleteCheckpoint(sessionID, checkpointID string) (*godo.HostedAgentCheckpointDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCheckpoint", sessionID, checkpointID)
	ret0, _ := ret[0].(*godo.HostedAgentCheckpointDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCheckpoint indicates an expected call of DeleteCheckpoint.
func (mr *MockHostedAgentsServiceMockRecorder) DeleteCheckpoint(sessionID, checkpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCheckpoint", reflect.TypeOf((*MockHostedAgentsService)(nil).DeleteCheckpoint), sessionID, checkpointID)
}

// DestroySession mocks base method.
func (m *MockHostedAgentsService) DestroySession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockHostedAgentsServiceMockRecorder) DestroySession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockHostedAgentsService)(nil).DestroySession), sessionID)
}

// ForkSession mocks base method.
func (m *MockHostedAgentsService) ForkSession(sessionID string, fork *godo.HostedAgentForkSessionRequest) ([]do.HostedAgentSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkSession", sessionID, fork)
	ret0, _ := ret[0].([]do.HostedAgentSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkSession indicates an expected call of ForkSession.
func (mr *MockHostedAgentsServiceMockRecorder) ForkSession(sessionID, fork any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkSession", reflect.TypeOf((*MockHostedAgentsService)(nil).ForkSession), sessionID, fork)
}

// GetCheckpoint mocks base method.
func (m *MockHostedAgentsService) GetCheckpoint(sessionID, checkpointID string) (*godo.HostedAgentCheckpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckpoint", sessionID, checkpointID)
	ret0, _ := ret[0].(*godo.HostedAgentCheckpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckpoint indicates an expected call of GetCheckpoint.
func (mr *MockHostedAgentsServiceMockRecorder) GetCheckpoint(sessionID, checkpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckpoint", reflect.TypeOf((*MockHostedAgentsService)(nil).GetCheckpoint), sessionID, checkpointID)
}

// GetSession mocks base method.
func (m *MockHostedAgentsService) GetSession(sessionID string) (*do.HostedAgentSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*do.HostedAgentSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockHostedAgentsServiceMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockHostedAgentsService)(nil).GetSession), sessionID)
}

// GetWorkspaceTransfer mocks base method.
func (m *MockHostedAgentsService) GetWorkspaceTransfer(sessionID, transferID string) (*godo.HostedAgentWorkspaceTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceTransfer", sessionID, transferID)
	ret0, _ := ret[0].(*godo.HostedAgentWorkspaceTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceTransfer indicates an expected call of GetWorkspaceTransfer.
func (mr *MockHostedAgentsServiceMockRecorder) GetWorkspaceTransfer(sessionID, transferID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceTransfer", reflect.TypeOf((*MockHostedAgentsService)(nil).GetWorkspaceTransfer), sessionID, transferID)
}

// ListCheckpoints mocks base method.
func (m *MockHostedAgentsService) ListCheckpoints(sessionID string, opt *godo.HostedAgentCheckpointListOptions) ([]godo.HostedAgentCheckpoint, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCheckpoints", sessionID, opt)
	ret0, _ := ret[0].([]godo.HostedAgentCheckpoint)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCheckpoints indicates an expected call of ListCheckpoints.
func (mr *MockHostedAgentsServiceMockRecorder) ListCheckpoints(sessionID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckpoints", reflect.TypeOf((*MockHostedAgentsService)(nil).ListCheckpoints), sessionID, opt)
}

// ListSessions mocks base method.
func (m *MockHostedAgentsService) ListSessions(arg0 *godo.HostedAgentSessionListOptions) ([]do.HostedAgentSession, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", arg0)
	ret0, _ := ret[0].([]do.HostedAgentSession)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockHostedAgentsServiceMockRecorder) ListSessions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockHostedAgentsService)(nil).ListSessions), arg0)
}

// PauseSession mocks base method.
func (m *MockHostedAgentsService) PauseSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSession indicates an expected call of PauseSession.
func (mr *MockHostedAgentsServiceMockRecorder) PauseSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSession", reflect.TypeOf((*MockHostedAgentsService)(nil).PauseSession), sessionID)
}

// PollProviderAuth mocks base method.
func (m *MockHostedAgentsService) PollProviderAuth(provider, pollURL string) (*godo.HostedAgentProviderAuthPoll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollProviderAuth", provider, pollURL)
	ret0, _ := ret[0].(*godo.HostedAgentProviderAuthPoll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollProviderAuth indicates an expected call of PollProviderAuth.
func (mr *MockHostedAgentsServiceMockRecorder) PollProviderAuth(provider, pollURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollProviderAuth", reflect.TypeOf((*MockHostedAgentsService)(nil).PollProviderAuth), provider, pollURL)
}

// RelayRequest mocks base method.
func (m *MockHostedAgentsService) RelayRequest(ctx context.Context, sessionID string, body *godo.HostedAgentRelayRequest) (*godo.HostedAgentRelayResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelayRequest", ctx, sessionID, body)
	ret0, _ := ret[0].(*godo.HostedAgentRelayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelayRequest indicates an expected call of RelayRequest.
func (mr *MockHostedAgentsServiceMockRecorder) RelayRequest(ctx, sessionID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelayRequest", reflect.TypeOf((*MockHostedAgentsService)(nil).RelayRequest), ctx, sessionID, body)
}

// ResolveHITL mocks base method.
func (m *MockHostedAgentsService) ResolveHITL(sessionID, requestID string, body *godo.HostedAgentResolveHITLRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveHITL", sessionID, requestID, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveHITL indicates an expected call of ResolveHITL.
func (mr *MockHostedAgentsServiceMockRecorder) ResolveHITL(sessionID, requestID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveHITL", reflect.TypeOf((*MockHostedAgentsService)(nil).ResolveHITL), sessionID, requestID, body)
}

// ResumeSession mocks base method.
func (m *MockHostedAgentsService) ResumeSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSession indicates an expected call of ResumeSession.
func (mr *MockHostedAgentsServiceMockRecorder) ResumeSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSession", reflect.TypeOf((*MockHostedAgentsService)(nil).ResumeSession), sessionID)
}

// RollbackToCheckpoint mocks base method.
func (m *MockHostedAgentsService) RollbackToCheckpoint(sessionID, checkpointID string) (*do.HostedAgentSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackToCheckpoint", sessionID, checkpointID)
	ret0, _ := ret[0].(*do.HostedAgentSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackToCheckpoint indicates an expected call of RollbackToCheckpoint.
func (mr *MockHostedAgentsServiceMockRecorder) RollbackToCheckpoint(sessionID, checkpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackToCheckpoint", reflect.TypeOf((*MockHostedAgentsService)(nil).RollbackToCheckpoint), sessionID, checkpointID)
}

// SendInput mocks base method.
func (m *MockHostedAgentsService) SendInput(sessionID string, input *godo.HostedAgentSendInputRequest) (*godo.HostedAgentSendInputResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInput", sessionID, input)
	ret0, _ := ret[0].(*godo.HostedAgentSendInputResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendInput indicates an expected call of SendInput.
func (mr *MockHostedAgentsServiceMockRecorder) SendInput(sessionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInput", reflect.TypeOf((*MockHostedAgentsService)(nil).SendInput), sessionID, input)
}

// StartProviderAuth mocks base method.
func (m *MockHostedAgentsService) StartProviderAuth(provider string) (*godo.HostedAgentProviderAuthStart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProviderAuth", provider)
	ret0, _ := ret[0].(*godo.HostedAgentProviderAuthStart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartProviderAuth indicates an expected call of StartProviderAuth.
func (mr *MockHostedAgentsServiceMockRecorder) StartProviderAuth(provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProviderAuth", reflect.TypeOf((*MockHostedAgentsService)(nil).StartProviderAuth), provider)
}

// StreamSession mocks base method.
func (m *MockHostedAgentsService) StreamSession(ctx context.Context, sessionID string, opt *godo.HostedAgentSessionStreamOptions) (*godo.HostedAgentSessionStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamSession", ctx, sessionID, opt)
	ret0, _ := ret[0].(*godo.HostedAgentSessionStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamSession indicates an expected call of StreamSession.
func (mr *MockHostedAgentsServiceMockRecorder) StreamSession(ctx, sessionID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamSession", reflect.TypeOf((*MockHostedAgentsService)(nil).StreamSession), ctx, sessionID, opt)
}
