// Code generated by MockGen. DO NOT EDIT.
// Source: inference.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockInferenceService is a mock of InferenceService interface.
type MockInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockInferenceServiceMockRecorder
}

// MockInferenceServiceMockRecorder is the mock recorder for MockInferenceService.
type MockInferenceServiceMockRecorder struct {
	mock *MockInferenceService
}

// NewMockInferenceService creates a new mock instance.
func NewMockInferenceService(ctrl *gomock.Controller) *MockInferenceService {
	mock := &MockInferenceService{ctrl: ctrl}
	mock.recorder = &MockInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInferenceService) EXPECT() *MockInferenceServiceMockRecorder {
	return m.recorder
}

// CreateAsyncInvocation mocks base method.
func (m *MockInferenceService) CreateAsyncInvocation(params *godo.AsyncInvocationNewParams) (*godo.AsyncInvocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsyncInvocation", params)
	ret0, _ := ret[0].(*godo.AsyncInvocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsyncInvocation indicates an expected call of CreateAsyncInvocation.
func (mr *MockInferenceServiceMockRecorder) CreateAsyncInvocation(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsyncInvocation", reflect.TypeOf((*MockInferenceService)(nil).CreateAsyncInvocation), params)
}

// CreateChatCompletion mocks base method.
func (m *MockInferenceService) CreateChatCompletion(params *godo.ChatCompletionNewParams) (*godo.ChatCompletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletion", params)
	ret0, _ := ret[0].(*godo.ChatCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletion indicates an expected call of CreateChatCompletion.
func (mr *MockInferenceServiceMockRecorder) CreateChatCompletion(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletion", reflect.TypeOf((*MockInferenceService)(nil).CreateChatCompletion), params)
}

// CreateChatCompletionStreaming mocks base method.
func (m *MockInferenceService) CreateChatCompletionStreaming(params *godo.ChatCompletionNewParams) (*godo.ChatCompletionStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletionStreaming", params)
	ret0, _ := ret[0].(*godo.ChatCompletionStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletionStreaming indicates an expected call of CreateChatCompletionStreaming.
func (mr *MockInferenceServiceMockRecorder) CreateChatCompletionStreaming(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletionStreaming", reflect.TypeOf((*MockInferenceService)(nil).CreateChatCompletionStreaming), params)
}

// CreateEmbedding mocks base method.
func (m *MockInferenceService) CreateEmbedding(params *godo.EmbeddingNewParams) (*godo.CreateEmbeddingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmbedding", params)
	ret0, _ := ret[0].(*godo.CreateEmbeddingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmbedding indicates an expected call of CreateEmbedding.
func (mr *MockInferenceServiceMockRecorder) CreateEmbedding(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmbedding", reflect.TypeOf((*MockInferenceService)(nil).CreateEmbedding), params)
}

// CreateMessage mocks base method.
func (m *MockInferenceService) CreateMessage(params *godo.MessageNewParams) (*godo.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", params)
	ret0, _ := ret[0].(*godo.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockInferenceServiceMockRecorder) CreateMessage(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockInferenceService)(nil).CreateMessage), params)
}

// CreateMessageStreaming mocks base method.
func (m *MockInferenceService) CreateMessageStreaming(params *godo.MessageNewParams) (*godo.MessageStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessageStreaming", params)
	ret0, _ := ret[0].(*godo.MessageStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessageStreaming indicates an expected call of CreateMessageStreaming.
func (mr *MockInferenceServiceMockRecorder) CreateMessageStreaming(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessageStreaming", reflect.TypeOf((*MockInferenceService)(nil).CreateMessageStreaming), params)
}

// CreateResponse mocks base method.
func (m *MockInferenceService) CreateResponse(params *godo.ResponseNewParams) (*godo.ResponsesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResponse", params)
	ret0, _ := ret[0].(*godo.ResponsesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResponse indicates an expected call of CreateResponse.
func (mr *MockInferenceServiceMockRecorder) CreateResponse(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResponse", reflect.TypeOf((*MockInferenceService)(nil).CreateResponse), params)
}

// CreateResponseStreaming mocks base method.
func (m *MockInferenceService) CreateResponseStreaming(params *godo.ResponseNewParams) (*godo.ResponseStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResponseStreaming", params)
	ret0, _ := ret[0].(*godo.ResponseStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResponseStreaming indicates an expected call of CreateResponseStreaming.
func (mr *MockInferenceServiceMockRecorder) CreateResponseStreaming(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResponseStreaming", reflect.TypeOf((*MockInferenceService)(nil).CreateResponseStreaming), params)
}

// GenerateImage mocks base method.
func (m *MockInferenceService) GenerateImage(params *godo.ImageGenerateParams) (*godo.ImagesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateImage", params)
	ret0, _ := ret[0].(*godo.ImagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateImage indicates an expected call of GenerateImage.
func (mr *MockInferenceServiceMockRecorder) GenerateImage(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateImage", reflect.TypeOf((*MockInferenceService)(nil).GenerateImage), params)
}

// GenerateImageStreaming mocks base method.
func (m *MockInferenceService) GenerateImageStreaming(params *godo.ImageGenerateParams) (*godo.ImageGenerationStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateImageStreaming", params)
	ret0, _ := ret[0].(*godo.ImageGenerationStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateImageStreaming indicates an expected call of GenerateImageStreaming.
func (mr *MockInferenceServiceMockRecorder) GenerateImageStreaming(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateImageStreaming", reflect.TypeOf((*MockInferenceService)(nil).GenerateImageStreaming), params)
}

// GetAsyncInvocation mocks base method.
func (m *MockInferenceService) GetAsyncInvocation(requestID string) (*godo.AsyncInvocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsyncInvocation", requestID)
	ret0, _ := ret[0].(*godo.AsyncInvocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsyncInvocation indicates an expected call of GetAsyncInvocation.
func (mr *MockInferenceServiceMockRecorder) GetAsyncInvocation(requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsyncInvocation", reflect.TypeOf((*MockInferenceService)(nil).GetAsyncInvocation), requestID)
}

// ListModels mocks base method.
func (m *MockInferenceService) ListModels() (*godo.ModelList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels")
	ret0, _ := ret[0].(*godo.ModelList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockInferenceServiceMockRecorder) ListModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockInferenceService)(nil).ListModels))
}
