// Code generated by MockGen. DO NOT EDIT.
// Source: microdroplets.go
//
// Generated by this command:
//
//	mockgen -source microdroplets.go -package=mocks MicroDropletsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockMicroDropletsService is a mock of MicroDropletsService interface.
type MockMicroDropletsService struct {
	ctrl     *gomock.Controller
	recorder *MockMicroDropletsServiceMockRecorder
	isgomock struct{}
}

// MockMicroDropletsServiceMockRecorder is the mock recorder for MockMicroDropletsService.
type MockMicroDropletsServiceMockRecorder struct {
	mock *MockMicroDropletsService
}

// NewMockMicroDropletsService creates a new mock instance.
func NewMockMicroDropletsService(ctrl *gomock.Controller) *MockMicroDropletsService {
	mock := &MockMicroDropletsService{ctrl: ctrl}
	mock.recorder = &MockMicroDropletsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicroDropletsService) EXPECT() *MockMicroDropletsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMicroDropletsService) Create(req *godo.MicroDropletCreateRequest) (*do.MicroDroplet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*do.MicroDroplet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMicroDropletsServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMicroDropletsService)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockMicroDropletsService) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMicroDropletsServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMicroDropletsService)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockMicroDropletsService) Get(id string) (*do.MicroDroplet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*do.MicroDroplet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMicroDropletsServiceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMicroDropletsService)(nil).Get), id)
}

// List mocks base method.
func (m *MockMicroDropletsService) List() (do.MicroDroplets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(do.MicroDroplets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMicroDropletsServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMicroDropletsService)(nil).List))
}

// ListByName mocks base method.
func (m *MockMicroDropletsService) ListByName(name string) (do.MicroDroplets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByName", name)
	ret0, _ := ret[0].(do.MicroDroplets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByName indicates an expected call of ListByName.
func (mr *MockMicroDropletsServiceMockRecorder) ListByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByName", reflect.TypeOf((*MockMicroDropletsService)(nil).ListByName), name)
}

// ListByRegion mocks base method.
func (m *MockMicroDropletsService) ListByRegion(region string) (do.MicroDroplets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRegion", region)
	ret0, _ := ret[0].(do.MicroDroplets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRegion indicates an expected call of ListByRegion.
func (mr *MockMicroDropletsServiceMockRecorder) ListByRegion(region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRegion", reflect.TypeOf((*MockMicroDropletsService)(nil).ListByRegion), region)
}

// ListSnapshots mocks base method.
func (m *MockMicroDropletsService) ListSnapshots(id string) (do.MicroDropletSnapshots, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshots", id)
	ret0, _ := ret[0].(do.MicroDropletSnapshots)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockMicroDropletsServiceMockRecorder) ListSnapshots(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockMicroDropletsService)(nil).ListSnapshots), id)
}

// Update mocks base method.
func (m *MockMicroDropletsService) Update(id string, req *godo.MicroDropletUpdateRequest) (*do.MicroDroplet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*do.MicroDroplet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMicroDropletsServiceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMicroDropletsService)(nil).Update), id, req)
}
