// Code generated by MockGen. DO NOT EDIT.
// Source: nfs_actions.go
//
// Generated by this command:
//
//	mockgen -source nfs_actions.go -package=mocks NfsActionsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	gomock "go.uber.org/mock/gomock"
)

// MockNfsActionsService is a mock of NfsActionsService interface.
type MockNfsActionsService struct {
	ctrl     *gomock.Controller
	recorder *MockNfsActionsServiceMockRecorder
	isgomock struct{}
}

// MockNfsActionsServiceMockRecorder is the mock recorder for MockNfsActionsService.
type MockNfsActionsServiceMockRecorder struct {
	mock *MockNfsActionsService
}

// NewMockNfsActionsService creates a new mock instance.
func NewMockNfsActionsService(ctrl *gomock.Controller) *MockNfsActionsService {
	mock := &MockNfsActionsService{ctrl: ctrl}
	mock.recorder = &MockNfsActionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNfsActionsService) EXPECT() *MockNfsActionsServiceMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockNfsActionsService) Attach(id, vpcID, region string) (*do.NfsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", id, vpcID, region)
	ret0, _ := ret[0].(*do.NfsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockNfsActionsServiceMockRecorder) Attach(id, vpcID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockNfsActionsService)(nil).Attach), id, vpcID, region)
}

// Detach mocks base method.
func (m *MockNfsActionsService) Detach(id, vpcID, region string) (*do.NfsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", id, vpcID, region)
	ret0, _ := ret[0].(*do.NfsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detach indicates an expected call of Detach.
func (mr *MockNfsActionsServiceMockRecorder) Detach(id, vpcID, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockNfsActionsService)(nil).Detach), id, vpcID, region)
}

// Resize mocks base method.
func (m *MockNfsActionsService) Resize(id string, size uint64, region string) (*do.NfsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", id, size, region)
	ret0, _ := ret[0].(*do.NfsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resize indicates an expected call of Resize.
func (mr *MockNfsActionsServiceMockRecorder) Resize(id, size, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockNfsActionsService)(nil).Resize), id, size, region)
}

// Snapshot mocks base method.
func (m *MockNfsActionsService) Snapshot(id, name, region string) (*do.NfsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", id, name, region)
	ret0, _ := ret[0].(*do.NfsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockNfsActionsServiceMockRecorder) Snapshot(id, name, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockNfsActionsService)(nil).Snapshot), id, name, region)
}

// SwitchPerformanceTier mocks base method.
func (m *MockNfsActionsService) SwitchPerformanceTier(id, tier string) (*do.NfsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchPerformanceTier", id, tier)
	ret0, _ := ret[0].(*do.NfsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwitchPerformanceTier indicates an expected call of SwitchPerformanceTier.
func (mr *MockNfsActionsServiceMockRecorder) SwitchPerformanceTier(id, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchPerformanceTier", reflect.TypeOf((*MockNfsActionsService)(nil).SwitchPerformanceTier), id, tier)
}
