// Code generated by MockGen. DO NOT EDIT.
// Source: secrets.go
//
// Generated by this command:
//
//	mockgen -source secrets.go -package=mocks SecretsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsService is a mock of SecretsService interface.
type MockSecretsService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsServiceMockRecorder
	isgomock struct{}
}

// MockSecretsServiceMockRecorder is the mock recorder for MockSecretsService.
type MockSecretsServiceMockRecorder struct {
	mock *MockSecretsService
}

// NewMockSecretsService creates a new mock instance.
func NewMockSecretsService(ctrl *gomock.Controller) *MockSecretsService {
	mock := &MockSecretsService{ctrl: ctrl}
	mock.recorder = &MockSecretsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsService) EXPECT() *MockSecretsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecretsService) Create(arg0 *godo.SecretCreateRequest) (*do.SecretWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*do.SecretWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSecretsServiceMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretsService)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSecretsService) Delete(name, region string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name, region)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretsServiceMockRecorder) Delete(name, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretsService)(nil).Delete), name, region)
}

// Get mocks base method.
func (m *MockSecretsService) Get(name, region string) (*do.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name, region)
	ret0, _ := ret[0].(*do.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretsServiceMockRecorder) Get(name, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecretsService)(nil).Get), name, region)
}

// List mocks base method.
func (m *MockSecretsService) List() (*do.SecretsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(*do.SecretsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretsServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretsService)(nil).List))
}

// ListVersions mocks base method.
func (m *MockSecretsService) ListVersions(name, region string) (do.SecretVersions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", name, region)
	ret0, _ := ret[0].(do.SecretVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockSecretsServiceMockRecorder) ListVersions(name, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockSecretsService)(nil).ListVersions), name, region)
}

// Restore mocks base method.
func (m *MockSecretsService) Restore(name, region string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", name, region)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockSecretsServiceMockRecorder) Restore(name, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockSecretsService)(nil).Restore), name, region)
}

// Update mocks base method.
func (m *MockSecretsService) Update(name string, req *godo.SecretUpdateRequest) (*do.SecretWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", name, req)
	ret0, _ := ret[0].(*do.SecretWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSecretsServiceMockRecorder) Update(name, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecretsService)(nil).Update), name, req)
}
