// Code generated by MockGen. DO NOT EDIT.
// Source: security.go
//
// Generated by this command:
//
//	mockgen -source security.go -package=mocks SecurityService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityService is a mock of SecurityService interface.
type MockSecurityService struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityServiceMockRecorder
	isgomock struct{}
}

// MockSecurityServiceMockRecorder is the mock recorder for MockSecurityService.
type MockSecurityServiceMockRecorder struct {
	mock *MockSecurityService
}

// NewMockSecurityService creates a new mock instance.
func NewMockSecurityService(ctrl *gomock.Controller) *MockSecurityService {
	mock := &MockSecurityService{ctrl: ctrl}
	mock.recorder = &MockSecurityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityService) EXPECT() *MockSecurityServiceMockRecorder {
	return m.recorder
}

// CreateScan mocks base method.
func (m *MockSecurityService) CreateScan(arg0 *godo.CreateScanRequest) (*do.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScan", arg0)
	ret0, _ := ret[0].(*do.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScan indicates an expected call of CreateScan.
func (mr *MockSecurityServiceMockRecorder) CreateScan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScan", reflect.TypeOf((*MockSecurityService)(nil).CreateScan), arg0)
}

// GetLatestScan mocks base method.
func (m *MockSecurityService) GetLatestScan(arg0 *godo.ScanFindingsOptions) (*do.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestScan", arg0)
	ret0, _ := ret[0].(*do.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestScan indicates an expected call of GetLatestScan.
func (mr *MockSecurityServiceMockRecorder) GetLatestScan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestScan", reflect.TypeOf((*MockSecurityService)(nil).GetLatestScan), arg0)
}

// GetScan mocks base method.
func (m *MockSecurityService) GetScan(arg0 string, arg1 *godo.ScanFindingsOptions) (*do.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScan", arg0, arg1)
	ret0, _ := ret[0].(*do.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScan indicates an expected call of GetScan.
func (mr *MockSecurityServiceMockRecorder) GetScan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScan", reflect.TypeOf((*MockSecurityService)(nil).GetScan), arg0, arg1)
}

// ListFindingAffectedResources mocks base method.
func (m *MockSecurityService) ListFindingAffectedResources(arg0, arg1 string) (do.AffectedResources, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFindingAffectedResources", arg0, arg1)
	ret0, _ := ret[0].(do.AffectedResources)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFindingAffectedResources indicates an expected call of ListFindingAffectedResources.
func (mr *MockSecurityServiceMockRecorder) ListFindingAffectedResources(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFindingAffectedResources", reflect.TypeOf((*MockSecurityService)(nil).ListFindingAffectedResources), arg0, arg1)
}

// ListScans mocks base method.
func (m *MockSecurityService) ListScans() (do.Scans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScans")
	ret0, _ := ret[0].(do.Scans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScans indicates an expected call of ListScans.
func (mr *MockSecurityServiceMockRecorder) ListScans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScans", reflect.TypeOf((*MockSecurityService)(nil).ListScans))
}
