// Code generated by MockGen. DO NOT EDIT.
// Source: do/signals.go
//
// Generated by this command:
//
//	mockgen -source=do/signals.go -package=mocks -destination=do/mocks/SignalsService.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	do "github.com/digitalocean/doctl/do"
	godo "github.com/digitalocean/godo"
	gomock "go.uber.org/mock/gomock"
)

// MockSignalsService is a mock of SignalsService interface.
type MockSignalsService struct {
	ctrl     *gomock.Controller
	recorder *MockSignalsServiceMockRecorder
	isgomock struct{}
}

// MockSignalsServiceMockRecorder is the mock recorder for MockSignalsService.
type MockSignalsServiceMockRecorder struct {
	mock *MockSignalsService
}

// NewMockSignalsService creates a new mock instance.
func NewMockSignalsService(ctrl *gomock.Controller) *MockSignalsService {
	mock := &MockSignalsService{ctrl: ctrl}
	mock.recorder = &MockSignalsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalsService) EXPECT() *MockSignalsServiceMockRecorder {
	return m.recorder
}

// CreateDeletion mocks base method.
func (m *MockSignalsService) CreateDeletion(req *godo.SignalsCreateDeletionRequest) (*do.SignalsDeletion, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeletion", req)
	ret0, _ := ret[0].(*do.SignalsDeletion)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateDeletion indicates an expected call of CreateDeletion.
func (mr *MockSignalsServiceMockRecorder) CreateDeletion(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeletion", reflect.TypeOf((*MockSignalsService)(nil).CreateDeletion), req)
}

// CreateExport mocks base method.
func (m *MockSignalsService) CreateExport(req *godo.SignalsCreateExportRequest) (*do.SignalsExport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExport", req)
	ret0, _ := ret[0].(*do.SignalsExport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExport indicates an expected call of CreateExport.
func (mr *MockSignalsServiceMockRecorder) CreateExport(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExport", reflect.TypeOf((*MockSignalsService)(nil).CreateExport), req)
}

// GetConsent mocks base method.
func (m *MockSignalsService) GetConsent(agentID string) (*do.SignalsAgentConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsent", agentID)
	ret0, _ := ret[0].(*do.SignalsAgentConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsent indicates an expected call of GetConsent.
func (mr *MockSignalsServiceMockRecorder) GetConsent(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsent", reflect.TypeOf((*MockSignalsService)(nil).GetConsent), agentID)
}

// GetDeletion mocks base method.
func (m *MockSignalsService) GetDeletion(deletionID string) (*do.SignalsDeletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletion", deletionID)
	ret0, _ := ret[0].(*do.SignalsDeletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletion indicates an expected call of GetDeletion.
func (mr *MockSignalsServiceMockRecorder) GetDeletion(deletionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletion", reflect.TypeOf((*MockSignalsService)(nil).GetDeletion), deletionID)
}

// GetExport mocks base method.
func (m *MockSignalsService) GetExport(exportID string) (*do.SignalsExport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExport", exportID)
	ret0, _ := ret[0].(*do.SignalsExport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExport indicates an expected call of GetExport.
func (mr *MockSignalsServiceMockRecorder) GetExport(exportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExport", reflect.TypeOf((*MockSignalsService)(nil).GetExport), exportID)
}

// GetExportDownload mocks base method.
func (m *MockSignalsService) GetExportDownload(exportID string) (*do.SignalsExportDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportDownload", exportID)
	ret0, _ := ret[0].(*do.SignalsExportDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportDownload indicates an expected call of GetExportDownload.
func (mr *MockSignalsServiceMockRecorder) GetExportDownload(exportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportDownload", reflect.TypeOf((*MockSignalsService)(nil).GetExportDownload), exportID)
}

// GetExportOptions mocks base method.
func (m *MockSignalsService) GetExportOptions() (*do.SignalsExportOptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportOptions")
	ret0, _ := ret[0].(*do.SignalsExportOptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportOptions indicates an expected call of GetExportOptions.
func (mr *MockSignalsServiceMockRecorder) GetExportOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportOptions", reflect.TypeOf((*MockSignalsService)(nil).GetExportOptions))
}

// GetInferenceConsent mocks base method.
func (m *MockSignalsService) GetInferenceConsent() (*do.SignalsConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInferenceConsent")
	ret0, _ := ret[0].(*do.SignalsConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInferenceConsent indicates an expected call of GetInferenceConsent.
func (mr *MockSignalsServiceMockRecorder) GetInferenceConsent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInferenceConsent", reflect.TypeOf((*MockSignalsService)(nil).GetInferenceConsent))
}

// GetTeamID mocks base method.
func (m *MockSignalsService) GetTeamID() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamID")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamID indicates an expected call of GetTeamID.
func (mr *MockSignalsServiceMockRecorder) GetTeamID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamID", reflect.TypeOf((*MockSignalsService)(nil).GetTeamID))
}

// ListAgentSessions mocks base method.
func (m *MockSignalsService) ListAgentSessions(agentID string, opts *godo.SignalsListAgentSessionsOptions) (do.SignalsSessions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentSessions", agentID, opts)
	ret0, _ := ret[0].(do.SignalsSessions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentSessions indicates an expected call of ListAgentSessions.
func (mr *MockSignalsServiceMockRecorder) ListAgentSessions(agentID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentSessions", reflect.TypeOf((*MockSignalsService)(nil).ListAgentSessions), agentID, opts)
}

// ListConsents mocks base method.
func (m *MockSignalsService) ListConsents() (do.SignalsConsents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsents")
	ret0, _ := ret[0].(do.SignalsConsents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsents indicates an expected call of ListConsents.
func (mr *MockSignalsServiceMockRecorder) ListConsents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsents", reflect.TypeOf((*MockSignalsService)(nil).ListConsents))
}

// ListConsentsBySource mocks base method.
func (m *MockSignalsService) ListConsentsBySource(source string) (do.SignalsConsents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsentsBySource", source)
	ret0, _ := ret[0].(do.SignalsConsents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsentsBySource indicates an expected call of ListConsentsBySource.
func (mr *MockSignalsServiceMockRecorder) ListConsentsBySource(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsentsBySource", reflect.TypeOf((*MockSignalsService)(nil).ListConsentsBySource), source)
}

// ListDeletions mocks base method.
func (m *MockSignalsService) ListDeletions(opts *godo.SignalsListDeletionsOptions) (do.SignalsDeletions, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeletions", opts)
	ret0, _ := ret[0].(do.SignalsDeletions)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDeletions indicates an expected call of ListDeletions.
func (mr *MockSignalsServiceMockRecorder) ListDeletions(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeletions", reflect.TypeOf((*MockSignalsService)(nil).ListDeletions), opts)
}

// ListExports mocks base method.
func (m *MockSignalsService) ListExports(opts *godo.SignalsListExportsOptions) (do.SignalsExports, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExports", opts)
	ret0, _ := ret[0].(do.SignalsExports)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExports indicates an expected call of ListExports.
func (mr *MockSignalsServiceMockRecorder) ListExports(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExports", reflect.TypeOf((*MockSignalsService)(nil).ListExports), opts)
}

// ListSessionDialogues mocks base method.
func (m *MockSignalsService) ListSessionDialogues(sessionID string, opts *godo.SignalsListDialoguesOptions) (do.SignalsSessionDialogues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionDialogues", sessionID, opts)
	ret0, _ := ret[0].(do.SignalsSessionDialogues)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionDialogues indicates an expected call of ListSessionDialogues.
func (mr *MockSignalsServiceMockRecorder) ListSessionDialogues(sessionID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionDialogues", reflect.TypeOf((*MockSignalsService)(nil).ListSessionDialogues), sessionID, opts)
}

// SetConsent mocks base method.
func (m *MockSignalsService) SetConsent(agentID string, enabled bool) (*do.SignalsConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConsent", agentID, enabled)
	ret0, _ := ret[0].(*do.SignalsConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetConsent indicates an expected call of SetConsent.
func (mr *MockSignalsServiceMockRecorder) SetConsent(agentID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConsent", reflect.TypeOf((*MockSignalsService)(nil).SetConsent), agentID, enabled)
}

// SetInferenceConsent mocks base method.
func (m *MockSignalsService) SetInferenceConsent(enabled bool) (*do.SignalsConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInferenceConsent", enabled)
	ret0, _ := ret[0].(*do.SignalsConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInferenceConsent indicates an expected call of SetInferenceConsent.
func (mr *MockSignalsServiceMockRecorder) SetInferenceConsent(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInferenceConsent", reflect.TypeOf((*MockSignalsService)(nil).SetInferenceConsent), enabled)
}
