name: doctl
version: edge
confinement: strict
summary: DigitalOcean's command line interface for the API
description: doctl is a command line interface for the DigitalOcean API. Use "doctl [command] --help" for more information about a command.

apps:
  doctl:
    command: doctl
    plugs: [network, network-bind]

parts:
  doctl:
    plugin: nil

    organize: 
        ../../../doctl: doctl
