name: doctl
version: "1.18.0"
summary: A command line tool for DigitalOcean services
description: doctl is a command line tool for DigitalOcean servics using the API.

grade: devel
confinement: strict

build-packages:
  - gcc
  - git

parts:
  go:
    source-tag: go1.11.4
  doctl:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]

apps:
  doctl:
    command: bin/doctl
    plugs: [network, home]
