name: doctl
version: git
summary: A command line tool for DigitalOcean services
description: doctl is a command line tool for DigitalOcean services using the API.

grade: stable
confinement: strict

build-packages:
  - gcc
  - git

parts:
  launcher:
    source: snap/local
    plugin: dump
    organize:
      '*': bin/
    override-stage: |
      cd $SNAPCRAFT_PART_INSTALL
      chmod +x bin/doctl-launch
      snapcraftctl stage
  doctl:
    after: [launcher]
    source: .
    plugin: go
    go-importpath: github.com/digitalocean/doctl
    go-packages: [github.com/digitalocean/doctl/cmd/doctl]
    override-pull: |
      git clone https://github.com/digitalocean/doctl.git .
    override-build: |
      version=$(scripts/version.sh)
      snapcraftctl set-version ${version}

      short=${version%+*}
      short=${short%-*}
      baseFlag="-X github.com/digitalocean/doctl"
      ldFlags="${baseFlag}.Label=release ${baseFlag}.Build=$(git rev-parse --short HEAD)"
      ldFlags="${ldFlags} ${baseFlag}.Major=$(echo ${short} | cut -d'.' -f1)"
      ldFlags="${ldFlags} ${baseFlag}.Minor=$(echo ${short} | cut -d'.' -f2)"
      ldFlags="${ldFlags} ${baseFlag}.Patch=$(echo ${short} | cut -d'.' -f3 | cut -d'+' -f1)"

      GO111MODULE=on CGO_ENABLED=0 go build -ldflags "${ldFlags}" -mod=vendor -o doctl cmd/doctl/main.go

      chmod +x doctl
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv doctl $SNAPCRAFT_PART_INSTALL/bin/
    organize:
      bin/doctl: bin/doctl.real

plugs:
  doctl-config:
    interface: personal-files
    write:
      - $HOME/.config/doctl
  kube-config:
    interface: personal-files
    write:
      - $HOME/.kube/

apps:
  doctl:
    command: bin/doctl-launch
    plugs:
      - home
      - network
      - ssh-keys
      - doctl-config
      - kube-config
